project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Statistical Learning Methods"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: modules.qmd
        text: Modules