project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Statistical Learning Methods"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Module 1"
        menu:
          - href: module-01/notes1.qmd
            text: "Notes 1: Introduction to Statistical Models"
          - href: module-01/notes2.qmd
            text: "Notes 2: R Tools"
      - text: "Module 2"
        menu:
          - text: "Notes 1: ..."
      - text: "Module 3"
        menu:
          - text: "Notes 1: ..."
      - text: "Module 4"
        menu:
          - text: "Notes 1: ..."
      - text: "Module 5"
        menu:
          - text: "Notes 1: ..."
      - text: "Module 6"
        menu:
          - text: "Notes 1: ..."
      - text: "Module 7"
        menu:
          - text: "Notes 1: ..."
      - text: "Module 8"
        menu:
          - text: "Notes 1: ..."