---
title: "Course page for Math 133: Statistical Learning Methods"
author: "John Mayberry"
---

## About This Course

Close your eyes and think of a time you tried to predict something. What was it it that you were trying to predict? Was it a number? Was it a binary outcome (like win/lose)? What information did you use to make your prediction?

In this class, prediction will be our goal and we'll develop a toolbox of methods for predicting one variable (called an **outcome** or **response** variable) from others (called **features** or **predictors**). We'll cover two main types of problems: **regression** (predicting a number, like a grade point average) and **classification** (predicting a category, like whether or not you pass a class). Along the way, you'll get hands-on experience building and evaluating a wide range of popular models, from foundational ones like linear and logistic regression to more modern approaches like ensemble methods and neural networks.

## What Will We Cover?

The three primary learning objectives for this course are as follows:

1.  **Describe, implement, and compare common predictive models in statistics (Develop Tools)**

    -   Linear models, including ordinary least squares and logistic regression

    -   Shrinkage methods, such as Ridge and Lasso regression

    -   K-nearest neighbors regression and classification

    -   Classification and regression trees

    -   Principal Component Analysis

    -   Clustering algorithms

    -   Random forests

    -   Gradient boosted models

    -   Neural networks

    -   Models with serial correlation (eg. Random walks, autoregressive models, moving average models)

2.  **Select the most applicable statistical tool given a specified research objective (Select Tools)**

    -   Distinguishing between regression and classification problems

    -   Distinguishing between supervised and unsupervised algorithms

    -   Evaluating model performance

    -   Model training and validation

    -   Resampling methods

    -   Variable selection
    
    -   Hyperparameter tuning

    -   Autocorrelation functions and stationarity

3.  **Communicate the results of predictive analyses with verbal, visual, and numerical descriptions**

    -   Calculate summary statistics and create tables in R
    
    -   Interpret model output in R
    
    -   Create appropriate figures using the `ggplot2` package in R

    -   Present results using notebooks style programs (eg. quarto, google collab)

All of this will be done in **R**, a widely used programming language in statistics and data science, so you'll leave the course with both the conceptual understanding and the practical coding skills that are valued in industry and graduate school.

## Who Is This Course For?

This course is designed for an audience with some basic background in both coding and statistics, but you don't need to be an expert in either. Specifically we assume:

-   **Coding:** You are familiar with fundamental programming concepts like variables, lists, and functions. Some prior experience with R is helpful but not required.
-   **Statistics:** You have some introductory statistics knowledge, such as familiarity with measures of center and spread (eg. mean, standard deviation), the normal distribution, and basic graphical displays (eg. histograms, scatterplots). We won't be starting from scratch on the statistical side but we also won't assume anything beyond the basics.

If that sounds like you, you're in the right place! For students with a little more math background (calculus and linear algebra), we've also included some supplementary sections in each module to demonstrate the magical theoretical underpinnings of our algorithms.

## Where to find course materials

All course notes will be posted here while all course assignments will be posted on Canvas. For additional resources, please click on the links below.

-   [Datasets](https://github.com/jmayberr/math133-stat-learning-fall2026/tree/main/Datasets)
-   [Module 1 Code Files](https://github.com/jmayberr/math133-stat-learning-fall2026/tree/main/module-01)

If you're still here, let's get cooking!
