---
title: "Class Notes for 10-07"
format: html
---

Load nfl player data regular season data from 2025 (RB, TE, WR)

```{r,message=F,warning=F}
library(nflreadr)
library(tidyverse)
fantasy2025 <- load_player_stats(2025, summary_level = "reg") |>
  dplyr::filter(position %in% c("TE","WR","RB")) |>
  select(player_display_name,recent_team,position,games,
         carries,rushing_yards,rushing_tds,
         receptions,targets,receiving_yards,receiving_tds,
         fantasy_points_ppr)
glimpse(fantasy2025)
```

Perform PCA

```{r}
football_pc=prcomp(fantasy2025[,4:12],scale=TRUE)
summary(football_pc)
```

Create Biplots:

```{r}
#Correlation
biplot(football_pc,
       xlabs = rep(".", nrow(fantasy2025)), #replaces row labels with .
       cex=0.5,    # Changes label sizes
       expand=1.1) #Expand vectors to create additional separation in labels
```

```{r}
#Distance
biplot(football_pc,scale=0)
```

Plot projection onto first two PCs with points colored by position and showing player name

```{r}
cb_palette <- c(
  "#000000",  # black
  "#E69F00",  # orange
  "#56B4E9",  # sky blue
  "#009E73",  # bluish green
  "#F0E442",  # yellow
  "#0072B2",  # blue
  "#D55E00",  # vermillion
  "#CC79A7"   # reddish purple
)
# COmbine component scores with dataset
fantasy2025_withPC=cbind(fantasy2025,football_pc$x)
fantasy2025_withPC |>
  ggplot(aes(x=PC1,y=PC2,col=position,label=player_display_name))+
  geom_point()+
  scale_color_manual(values=cb_palette[2:4])+
  geom_text()
```

Find a player

```{r}
ggplot(fantasy2025_withPC, aes(x = PC1, y = PC2, col = position)) +
  geom_point() +
  scale_color_manual(values = cb_palette[2:4]) +
  geom_point(
    data = subset(fantasy2025_withPC, player_display_name == "Bijan Robinson"),
    size = 4,
    color = "black"
  ) +
  geom_text(
    data = subset(fantasy2025_withPC, player_display_name == "Bijan Robinson"),
    aes(label = player_display_name),
    color = "black",
    vjust = -1
  )
```

Find a team

```{r}
ggplot(fantasy2025_withPC, aes(x = PC1, y = PC2, col = position)) +
  geom_point() +
  scale_color_manual(values = cb_palette[2:4]) +
  geom_point(
    data = subset(fantasy2025_withPC, recent_team == "SF"),
    size = 3,
    color = "black"
  ) +
  geom_text(
    data = subset(fantasy2025_withPC, recent_team == "SF"),
    aes(label = player_display_name),
    color = "black",
    vjust = -1
  )
```

Plotly tooltip (thanks to Ethan):

```{r}
library(plotly)
fant_plot=fantasy2025_withPC |>
  ggplot(aes(x=PC1,y=PC2,col=position,label=player_display_name))+
  geom_point()+
  scale_color_manual(values=cb_palette[2:4])
ggplotly(fant_plot,tooltip = "label")
```

Heatmap of Correlations:

```{r}
library(GGally)
ggcorr(fantasy2025_withPC[,4:21])
```

Scree plot

```{r}
#Std dev
scree=data.frame(Components=1:9,Std.dev=football_pc$sdev)
# Prop of Variance
scree = scree |>
  mutate(Prop.var=Std.dev^2/sum(football_pc$sdev^2))
scree |>
  ggplot(aes(x=Components,y=Prop.var))+
  geom_point()+
  geom_line()
```
