<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Module 5.1: Principal Component Analysis – Statistical Learning Methods</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d4be639c637f3db3c684c66cefad7e0c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Statistical Learning Methods</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-1" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 1</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-1">    
        <li>
    <a class="dropdown-item" href="../module-01/notes1.html">
 <span class="dropdown-text">Module 1.1: Introduction to Statistical Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-01/notes2.html">
 <span class="dropdown-text">Module 1.2: Prediction for Simple Linear Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-01/notes3.html">
 <span class="dropdown-text">Module 1.3: Inference for Simple Linear Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-01/supplement.html">
 <span class="dropdown-text">Module 1 Theory: A deeper look at finding coefficients</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-01/rtools.html">
 <span class="dropdown-text">Module 1 R Tools: Introduction to ggplot2 and tidyverse</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-2" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 2</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-2">    
        <li>
    <a class="dropdown-item" href="../module-02/notes1.html">
 <span class="dropdown-text">Module 2.1: Multiple Regression Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-02/notes2.html">
 <span class="dropdown-text">Module 2.2: Enriching Linear Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-02/notes3.html">
 <span class="dropdown-text">Module 2.3: Regression Diagnostics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-02/notes_bonus.html">
 <span class="dropdown-text">Module 2 Bonus: The F Test</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-02/supplement.html">
 <span class="dropdown-text">Module 2 Theory Supplement</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-3" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 3</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-3">    
        <li>
    <a class="dropdown-item" href="../module-03/notes1.html">
 <span class="dropdown-text">Module 3.1: Introduction to Classification</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-03/notes2.html">
 <span class="dropdown-text">Module 3.2: Logistic Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-03/notes3.html">
 <span class="dropdown-text">Module 3.3: Evaluating Classifiers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-03/supplement.html">
 <span class="dropdown-text">Module 3 Theory Supplement: Finding Logistic Regression Coefficients</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-4" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 4</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-4">    
        <li>
    <a class="dropdown-item" href="../module-04/notes1.html">
 <span class="dropdown-text">Module 4.1: Cross Validation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-04/notes2.html">
 <span class="dropdown-text">Module 4.2: Feature Selection</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-04/notes3.html">
 <span class="dropdown-text">Module 4.3: Regularization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-04/rTools.html">
 <span class="dropdown-text">Module 4 R Tools: Tuning Hyperparameters with Tidymodels</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-5" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 5</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-5">    
        <li>
    <a class="dropdown-item" href="../module-05/notes1.html">
 <span class="dropdown-text">Module 5.1: Principal Component Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-05/notes2.html">
 <span class="dropdown-text">Module 5.2: K-means Clustering</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-05/notes3.html">
 <span class="dropdown-text">Module 5.3: Hierarchical Clustering</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-05/supplement.html">
 <span class="dropdown-text">Module 5 Theory Supplement: PCA vs SVD</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-05/rtools.html">
 <span class="dropdown-text">Module 5 R Tools: fviz-ness</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-6" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 6</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-6">    
        <li>
    <a class="dropdown-item" href="../module-06/notes1.html">
 <span class="dropdown-text">Module 6.1: Regression Trees</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-06/notes2.html">
 <span class="dropdown-text">Module 6.2: Classification Trees</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-06/notes3.html">
 <span class="dropdown-text">Module 6.3: Random Forests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-06/rtools.qmd">
 <span class="dropdown-text">Module 6 R Tools: Return of Tidymodels</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-7" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 7</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-7">    
        <li class="dropdown-header">Notes 1: …</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-8" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 8</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-8">    
        <li class="dropdown-header">Notes 1: …</li>
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 5.1: Principal Component Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction-supervised-vs.-unsupervised-methods" class="level2">
<h2 class="anchored" data-anchor-id="introduction-supervised-vs.-unsupervised-methods">Introduction: Supervised vs.&nbsp;Unsupervised Methods</h2>
<p>Thus far in the course, all of our examples have taken the following flavor: we have some response variable <span class="math inline">\(Y\)</span> and some set of predictors <span class="math inline">\(X_1,...,X_p\)</span> which we want to use to predict <span class="math inline">\(Y\)</span>. For example, if <span class="math inline">\(Y\)</span> is numeric, we can use OLS or one of its cousins (subset selection, lasso, etc) to fit a linear model <span class="math inline">\(Y=XB+\varepsilon\)</span>. This is called a regression problem. If <span class="math inline">\(Y\)</span> is categorical, we can use logistic regression (or KNN) and this is called a classification problem.</p>
<p>Both regression and classification problems fall under the framework of <em>supervised</em> methods because models are fit based on a pre-specified target of responses. In contrast, <em>unsupervised</em> methods apply when you don’t know the outcomes. In such scenarios, the goal is to identify appropriate ways of grouping predictors. For example, Spotify may want to group together users based on past listening histories and then target groups with specific listening recommendations.</p>
<p>We will discuss two types of unsupervised methods in this module:</p>
<ul>
<li>Principal Component Analysis (PCA) where samples are grouped based on linear combinations of predictors.</li>
<li>Cluster Analysis where items are grouped based on similarities in variable measurements</li>
</ul>
<p>These notes will focus on the former because it also provides a smooth transition from the topic of last module as it is often used for “dimension reduction”. We’ll see this application later in the notes.</p>
</section>
<section id="idea-behind-principal-components" class="level2">
<h2 class="anchored" data-anchor-id="idea-behind-principal-components">Idea behind principal components</h2>
<p>We have frequently used the election2016 data set as an example of supervised learning using both the trump.vote proportion and outcome (red or blue) as response variables. But suppose our interest instead is not to predict, but just to group like states together for the purposes of political or economic planning. Is there a simple way of doing so based on the eight demographic-ish variables we previously used as predictors? First, let’s reload the dataset, tidyverse package, and my favorite colorblind friendly palette which we will use throughout this module:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>df_url<span class="ot">=</span><span class="st">"https://raw.githubusercontent.com/jmayberr/math133-stat-learning-fall2026/refs/heads/main/Datasets/election2016.csv"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>election2016<span class="ot">=</span><span class="fu">read.csv</span>(df_url)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>cb_palette <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#000000"</span>,  <span class="co"># black</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#E69F00"</span>,  <span class="co"># orange</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#56B4E9"</span>,  <span class="co"># sky blue</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#009E73"</span>,  <span class="co"># bluish green</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#F0E442"</span>,  <span class="co"># yellow</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#0072B2"</span>,  <span class="co"># blue</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#D55E00"</span>,  <span class="co"># vermillion</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#CC79A7"</span>   <span class="co"># reddish purple</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The states live in eight dimensional space<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> when looked at in this way so it might be a little hard to “see” any groupings. But as previously noted in Module 4.2, many of the predictors are heavily correlated with each other:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorr</span>(election2016[,<span class="dv">2</span><span class="sc">:</span><span class="dv">9</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notes1_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Looking at these graphics we can see, for example, that there is a very high positive correlation between non.white, non.citizen, and metro. Does it make sense to include all three variables in our model or is there a single variables (such as the average of the three) which might be sufficient to capture their combined effect?</p>
<p>Principal Component Analysis (PCA) attempts to find “optimal” linear combinations of predictors to use as alternative features in a linear model. In other words, PCA attempts to replace a set of predictors <span class="math inline">\(X_1,..,X_p\)</span> with a new set of variables <span class="math inline">\(U_1,..,U_q\)</span> such that the <span class="math inline">\(U_i\)</span> capture the essential information about the <span class="math inline">\(X_i\)</span>s but with a fewer number <span class="math inline">\(q &lt; p\)</span> variables. Whereas the original predictors <span class="math inline">\(X_i\)</span> may have correlations, we would like the <span class="math inline">\(U_i\)</span> to be uncorrelated with each other so that each is capturing as much of the variance in features as possible.</p>
</section>
<section id="the-rotation-matrix" class="level2">
<h2 class="anchored" data-anchor-id="the-rotation-matrix">The rotation matrix</h2>
<p>Let’s start by illustrating this idea with the two variables non.white and non.citizen. Our goal will be to represent each observation (non.white,non.citizen) in a new orthogonal coordinate system <span class="math inline">\((u_1,u_2)\)</span> such that the first coordinate captures as much of the spread as possible while the second coordinate picks up the remainder. In other words, we would like to create a new set of orthogonal directions for getting to a particular (non.white,non.citizen) pair which goes as far as possible in the first step and then only has minimal distance to travel in the second step. Amazingly, the choice of directions ends up being based on the least squares line.</p>
<p>Hopefully, a visual will help better explain this idea. First, here is a scatterplot of non.white vs non.citizen with the least squares line</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(election2016,<span class="fu">aes</span>(<span class="at">x=</span>non.white,<span class="at">y=</span>non.citizen))<span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape=</span><span class="dv">1</span>)<span class="sc">+</span><span class="fu">geom_smooth</span>(<span class="at">method=</span>lm,<span class="at">se=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notes1_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now suppose we “center” the two variables (so that the mean is at the origin) and also show the line orthogonal to the least squares one:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>xbar<span class="ot">=</span><span class="fu">mean</span>(election2016<span class="sc">$</span>non.white)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>ybar<span class="ot">=</span><span class="fu">mean</span>(election2016<span class="sc">$</span>non.citizen)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>m<span class="ot">=</span><span class="fu">coef</span>(<span class="fu">lm</span>(non.citizen<span class="sc">~</span>non.white,<span class="at">data=</span>election2016))[<span class="dv">2</span>]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(election2016,<span class="fu">aes</span>(<span class="at">x=</span>non.white<span class="sc">-</span>xbar,<span class="at">y=</span>non.citizen<span class="sc">-</span>ybar))<span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape=</span><span class="dv">1</span>)<span class="sc">+</span><span class="fu">geom_smooth</span>(<span class="at">method=</span>lm,<span class="at">se=</span><span class="cn">FALSE</span>)<span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span><span class="sc">-</span><span class="dv">1</span><span class="sc">/</span>m,<span class="at">color=</span><span class="st">"red"</span>)<span class="sc">+</span><span class="fu">coord_fixed</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notes1_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I just want to reach in there and rotate this so that the blue line is the new x-axis and the red is the new y. This type of transformation is called a change of basis in Linear Algebra and it is the basis of PCA (pun totally intended).</p>
<p>Changing bases allows us to give directions to a particular point <span class="math inline">\((x_1,x_2)\)</span> in new ways. Instead of “travel <span class="math inline">\(x_1\)</span> units left and <span class="math inline">\(x_2\)</span> units right”, we can travel <span class="math inline">\(u_1\)</span> units in the direction of the blue line and then <span class="math inline">\(u_2\)</span> in the direction of the red. For the data above, this seems more efficient: the blue direction covers more of the “spread” or “variance” in the data while the red helps get us the rest of the way home.</p>
<p>The coordinates <span class="math inline">\((u_1,u_2)\)</span> are called the Principal Component Scores of <span class="math inline">\((x_1,x_2)\)</span> while the directions given by the blue and red lines are the first and second principal components. Both the first and second principal components <span class="math inline">\(U_j\)</span> are linear combinations of <span class="math inline">\(X_1,X_2\)</span> so <span class="math display">\[
U_j = v_{1j} X_1 + v_{2j} X_2
\]</span> where here, <span class="math inline">\(X_1,X_2\)</span> refer to the centered versions of non.white and non.citizen. The coefficients <span class="math inline">\(v_{ij}\)</span> are called the <em>loadings</em> and the matrix <span class="math inline">\(V\)</span> containing the loadings is called the <em>rotation matrix</em> . They can be calculated using the prcomp function in R<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>states_pc<span class="ot">=</span><span class="fu">prcomp</span>(election2016[,<span class="fu">c</span>(<span class="st">"non.white"</span>,<span class="st">"non.citizen"</span>)])</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>states_pc<span class="sc">$</span>rotation</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   PC1        PC2
non.white   -0.9909546 -0.1341973
non.citizen -0.1341973  0.9909546</code></pre>
</div>
</div>
<p>The output here means that the first principal components loadings (column PC1 of rotation matrix) are <span class="math inline">\(-0.991\)</span> and <span class="math inline">\(-0.134\)</span> (rounded). More specifically, this means that that the first PC is computed as <span class="math display">\[
PC_1 = -0.991*(non.white-mean(non.white))-0.134*(non.citizen-mean(non.citizen))
\]</span></p>
<p>Similarly, the loadings for the second principal component are given by the second column of the loadings matrix. Notice that <span class="math inline">\(PC_1, PC_2\)</span> are orthogonal (the dot product of their loading vectors is 0) which is the geometric equivalent of uncorrelated. One can also get the PC coordinates for the original points as follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(states_pc<span class="sc">$</span>x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              PC1          PC2
[1,] -0.036072643 -0.036168003
[2,] -0.108123413 -0.025742719
[3,] -0.185542074  0.024320750
[4,]  0.050429329 -0.004271156
[5,] -0.308482548  0.037945717
[6,] -0.001802348  0.008838073</code></pre>
</div>
</div>
<p>These show the transformed coordinates for each observation in the dataset. For example, looking at the first state in our dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>election2016[<span class="dv">1</span>,<span class="fu">c</span>(<span class="st">"state"</span>,<span class="st">"non.white"</span>,<span class="st">"non.citizen"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    state non.white non.citizen
1 Alabama      0.35        0.02</code></pre>
</div>
</div>
<p>This state has been transformed to the new coordinates<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>states_pc<span class="sc">$</span>x[<span class="dv">1</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        PC1         PC2 
-0.03607264 -0.03616800 </code></pre>
</div>
</div>
</section>
<section id="biplots" class="level2">
<h2 class="anchored" data-anchor-id="biplots">Biplots</h2>
<p>An additional tool for visualizing the relationship between the rotated PCs and the original variables is called a biplot. There are two main types: distance and correlation. Both are based upon different scalings of the rotation matrix<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> The former emphasizes clustering of observations while the latter emphasizes correlations between variables. Correlation is the default so let’s look at that first:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">biplot</span>(states_pc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notes1_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The red vectors are the (scaled) coordinates of non.white and non.citizen in terms of (PC1, PC2). The acute angle between non.white and non.citizen indicates a positive correlation between the two variables.</p>
<p>For a distance biplot, switch to <code>scale=0</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">biplot</span>(states_pc,<span class="at">scale=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notes1_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now the angle between the variables is meaningless but the points are plotted at their coordinates in PC space; more on this shortly.</p>
</section>
<section id="explained-variance" class="level2">
<h2 class="anchored" data-anchor-id="explained-variance">Explained Variance</h2>
<p>As previously mentioned, one goal of principal components is to describe as much of the variance in our data as possible from as few components as possible. To quantify this in PCA, we look at the <em>proportion of variance</em> for component <span class="math inline">\(i\)</span> which is defined as <span class="math inline">\(s_i^2/\sum s_j^2\)</span> where <span class="math inline">\(s_i\)</span> is the standard deviation of component <span class="math inline">\(i\)</span>. Notice this is the variance of component <span class="math inline">\(i\)</span> divided by the total variance of all components. Using our output, we can calculate the proportion of variance explained by each PC using the command</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>states_pc<span class="sc">$</span>sdev<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="fu">sum</span>(states_pc<span class="sc">$</span>sdev<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.98146661 0.01853339</code></pre>
</div>
</div>
<p>Alternatively, you can get them from the summary function</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(states_pc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          PC1     PC2
Standard deviation     0.1617 0.02222
Proportion of Variance 0.9815 0.01853
Cumulative Proportion  0.9815 1.00000</code></pre>
</div>
</div>
<p>The results tell us that PC1 explains over 98% of the variance in (non.white,non.citizen) measurements and PC2 only gets about 2%. This can kind of be seen in the distance biplot where you’ll notice most points spread out along the <span class="math inline">\(x\)</span>-axis. We conclude that these two variables can be summarized by a single variable which is simply the first principal component.</p>
</section>
<section id="many-become-fewer" class="level2">
<h2 class="anchored" data-anchor-id="many-become-fewer">Many become fewer</h2>
<p>The PCA framework can easily extend to more than two predictors. For example, let’s look at the full principal component decomposition for our predictors in the election2016 dataset. Note that we are adding the <code>scale=TRUE</code> command which scales each variable by its standard deviation prior to computing the principal components. This is important here because the variable median.income is on a completely different scale than the other variables and would dominate the PCs if not scaled.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>states_pc_full<span class="ot">=</span><span class="fu">prcomp</span>(election2016[,<span class="dv">2</span><span class="sc">:</span><span class="dv">9</span>],<span class="at">scale=</span><span class="cn">TRUE</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(states_pc_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          PC1    PC2     PC3     PC4     PC5    PC6     PC7
Standard deviation     1.8543 1.6547 0.74950 0.69703 0.54924 0.4418 0.39268
Proportion of Variance 0.4298 0.3422 0.07022 0.06073 0.03771 0.0244 0.01927
Cumulative Proportion  0.4298 0.7720 0.84226 0.90300 0.94070 0.9651 0.98438
                           PC8
Standard deviation     0.35354
Proportion of Variance 0.01562
Cumulative Proportion  1.00000</code></pre>
</div>
</div>
<p>Notice that the first PC describes only about 43% of the predictor variance between states, but keep in mind that we are now trying to summarize eight variables with one so that’s better than the 12.5% we would get by just randomly choosing one of eight directions! The first two principal components together<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> explain more than 77% of the variance in all eight variables. After that, we don’t gain much per additional component.</p>
<p>These results suggest we may be able to summarize all eight predictors with just those first two specially chosen linear combinations given by PC1 and PC2. Let’s look at how those first two components are related to our original variables via a correlation biplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">biplot</span>(states_pc_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notes1_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Notice (feels like I am saying that a lot in these notes) how certain groups of variables are clustered together like non.citizen, metro, and non.white. This indicates the high amount of correlation between these variables. Vectors pointing in opposite directions indicate negative correlation (for example, white.pov and median.income). Vectors pointing in orthogonal directions indicate very little correlation (eg. high school and metro)</p>
<p>To interpret what PCs mean for the states, let’s switch to a distance plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">biplot</span>(states_pc_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notes1_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We make the following observations<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> * States with positive PC1 and PC2 (upper right) have high median income and high school graduation rates with low white.pov * States with positive PC1 but negative PC2 (upper left) are very metropolitan and diverse * States with negative PC1 and PC2 are poor and less educated with high unemployment and white.pov rates. * Points with positive PC1 but negative PC2 are very white and rural</p>
<p>With these observations in mind, let’s look at a plot of the PC scores labeled by states</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>electionPC<span class="ot">=</span><span class="fu">cbind</span>(election2016,states_pc_full<span class="sc">$</span>x[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>electionPC <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>PC1,<span class="at">y=</span>PC2,<span class="at">label=</span>state))<span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notes1_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>How do our observations about the meaning of the principal components match up with what you know about the states? We leave it to the reader to decide<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>.</p>
</section>
<section id="how-is-pca-unsupervised-learning" class="level2">
<h2 class="anchored" data-anchor-id="how-is-pca-unsupervised-learning">How is PCA unsupervised learning?</h2>
<p>So far, what we have done is start to visually group states together based on where they lay in this two-dimensional plot. Let’s do something a little more concrete by placing groups into “clusters” based on which quadrant they fall in:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>electionPC<span class="sc">$</span>cluster<span class="ot">=</span><span class="fu">ifelse</span>(electionPC<span class="sc">$</span>PC1<span class="sc">&gt;</span><span class="dv">0</span><span class="sc">&amp;</span>electionPC<span class="sc">$</span>PC2<span class="sc">&gt;</span><span class="dv">0</span>,<span class="st">"I"</span>,</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">ifelse</span>(electionPC<span class="sc">$</span>PC1<span class="sc">&lt;</span><span class="dv">0</span><span class="sc">&amp;</span>electionPC<span class="sc">$</span>PC2<span class="sc">&gt;</span><span class="dv">0</span>,<span class="st">"II"</span>,                                                             <span class="fu">ifelse</span>(electionPC<span class="sc">$</span>PC1<span class="sc">&lt;</span><span class="dv">0</span><span class="sc">&amp;</span>electionPC<span class="sc">$</span>PC2<span class="sc">&lt;</span><span class="dv">0</span>,<span class="st">"III"</span>,                                                           <span class="st">"IV"</span>)))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(electionPC,<span class="fu">aes</span>(<span class="at">x=</span>PC1,<span class="at">y=</span>PC2,<span class="at">label=</span>state,<span class="at">col=</span>cluster))<span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>()<span class="sc">+</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values=</span>cb_palette[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notes1_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#c("black","#e35205","#56B4e9","#009e73")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And voila, we have classified the states in some new and bizarre way. Is this useful? How the hell should I know? I’m just a mathematician. Go ask your political science buddies.</p>
</section>
<section id="pca-as-dimension-reduction" class="level2">
<h2 class="anchored" data-anchor-id="pca-as-dimension-reduction">PCA as dimension reduction</h2>
<p>PCA can also be used in feature selection, but with a very different approach from complexity metrics or regularization. Instead of trying to choose a subset of features, it tries to reduce the number of variables by removing unnecessary correlations. For example, suppose that we use the component scores in a model for trump.vote instead of our original eight features. These can be added to the original data using the following</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>electionPC_full<span class="ot">=</span><span class="fu">cbind</span>(election2016,states_pc_full<span class="sc">$</span>x)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(electionPC_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "state"         "median.income" "unemployed"    "metro"        
 [5] "high.school"   "non.citizen"   "white.pov"     "income.ineq"  
 [9] "non.white"     "trump.vote"    "outcome"       "PC1"          
[13] "PC2"           "PC3"           "PC4"           "PC5"          
[17] "PC6"           "PC7"           "PC8"          </code></pre>
</div>
</div>
<p>All eight PC score variables were added to the dataset. The full model for trump.vote had an <span class="math inline">\(R^2\)</span> value of around</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>full_lm<span class="ot">=</span><span class="fu">lm</span>(trump.vote<span class="sc">~</span>.,<span class="at">data=</span>election2016[,<span class="dv">2</span><span class="sc">:</span><span class="dv">10</span>])</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full_lm)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6510282</code></pre>
</div>
</div>
<p>Now suppose we use the first three PCs (which accounted for over 80% of the total variance):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>pcs_lm<span class="ot">=</span><span class="fu">lm</span>(trump.vote<span class="sc">~</span>PC1<span class="sc">+</span>PC2<span class="sc">+</span>PC3,<span class="at">data=</span>electionPC_full)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pcs_lm)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5354155</code></pre>
</div>
</div>
<p>Not too much worse. If you look at the best three variable model its better though:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>best3_lm<span class="ot">=</span><span class="fu">lm</span>(trump.vote<span class="sc">~</span>median.income<span class="sc">+</span>non.citizen<span class="sc">+</span>income.ineq,<span class="at">data=</span>electionPC_full)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(best3_lm)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.573087</code></pre>
</div>
</div>
<p>so maybe in this case dimension reduction is not the way to go. The problem is that PCA doesn’t do anything to account for the importance of variables in their explanation of trump.vote so there isn’t a great reason to expect its components do well as predictors. Another tool called <em>partial least squares</em> adjusts for predictive purposes, but we won’t have time to cover it in these notes<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>.</p>
</section>
<section id="issue-with-pca" class="level2">
<h2 class="anchored" data-anchor-id="issue-with-pca">Issue with PCA</h2>
<p>The problem with using PCA for unsupervised learning is twofold. First, there are no great rules for choosing how many PCs to look at in classifying points. A <em>scree plot</em> is one commonly used tool for this purpose which plots the standard deviations of the principal components (singular values of the centered model matrix/eigenvalues of the covariance matrix) vs component number and looks for “elbows<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a>”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>scree<span class="ot">=</span><span class="fu">data.frame</span>(<span class="at">Component=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>,<span class="at">Std.Dev=</span>states_pc_full<span class="sc">$</span>sdev )</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(scree,<span class="fu">aes</span>(<span class="at">x=</span>Component,<span class="at">y=</span>Std.Dev))<span class="sc">+</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">name=</span><span class="st">"Number of Principal Components"</span>, </span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">breaks=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>,<span class="at">label=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notes1_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It seems like this plot has an “elbow” around PC3 so we could justify using three principal components. On the other hand, it bends at a weird angle after tat so should the elbow be higher at 6? It’s inexact enough that you can see why it’s qualitative. Others use an exact cutoff to decide on PCs, for example, choose enough PCs to account for 90% of the variation. This is a little more quantitative but may add too many PCs. And once we get past two, we lose the powerful visualization tools of biplots anyways so there may not be much point.</p>
<p>A second issue with principal component analysis is deciding on boundaries between clusters of like points. For example, should Maryland and Hawaii really go with the other “black” states even though they are kind of off in their own little world? And some states that are pretty close together end up in different clusters (like Oregon and Delaware). Clustering methods get around this issue by developing an algorithm for “combining” points into “optimal clusters.” For these reasons, other algorithms which actually have clustering in the name are often preferable for unsupervised learning<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a>. Those will be the topic of the next two sections.</p>
</section>
<section id="practice" class="level2">
<h2 class="anchored" data-anchor-id="practice">Practice</h2>
<p>The dataset <a href="https://raw.githubusercontent.com/jmayberr/math133-stat-learning-fall2026/refs/heads/main/Datasets/pitchers.csv">pitchers.csv</a> in the shared folder has all complete observations of MLB pitchers by season from 1871-2021.</p>
<ol type="1">
<li>Perform PCA on columns 6-29 and look at the proportion of variance explained by each component. Is there a sharp drop-off (a scree plot could be helpful to see)?</li>
<li>Look at a correlation biplot (it may take a while to create and you may have to zoom in to see it better). Which variables are positively correlated? Which are negative? Which are uncorrelated? (You don’t have to list all; just give some examples)</li>
<li>Look at a distance biplot. What does it mean for pitchers to have positive PC1? What about negative PC2? If you know anything about baseball, any guesses what these components could represent?</li>
</ol>
<p><strong>Bonus Tasks</strong>:</p>
<ul>
<li>Define a new variable with takes on the value of “starter” if pitching.GS/pitching.G &gt;=0.5 and reliever otherwise. Replot the first two principal compoents colored by this new variable. Do the principal components seem to separate points?</li>
<li>Find Jeff Ridgeway, 2007 in the PC plot and look up his story. Do you think he’s proud of being an outlier?</li>
<li>Find Mike Marshall, 1974. Is he proud of being an outlier?</li>
</ul>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Even if all our states can be a bit one-dimensional at times.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Confusingly, there is another base function princomp which also does PCA, but in a less stable way; more on computation of principal components in the Module 5 Theory supplement<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Stored as x instead of scores for prcomp.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>See Module 5 Theory supplement for details.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>The <span class="math inline">\(i\)</span>th entry in the cumulative proportion row tells you the cumulative proportion of variance explained by the first <span class="math inline">\(i\)</span> components in case that isn’t obvious.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Notice I avoided saying notice again. Ah crap, I did it anyways.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>I can’t help but point out my home state of CA though which has the lowest value of PC1 and a high PC2. This is because CA is above average in diversity and metropolitan-ness (negative PC1) but has a high median income and low white poverty rate both of which require a high PC2 to offset the negative effects from PC1.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Gotta save some fun for those late night AI dives.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>The name scree plot comes from the connection to elbows.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>Although as we’ll see they can be used in conjunction with PCA.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>