{
  "hash": "c5fad0c9663ab6cab414544db46927f0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Module 2.2: Enriching Linear Models\"\n---\n\n\n\n## Introduction\n\nThis section will focus on three additions to the multiple regression models discussed in the last section:\n\n-   Qualitative predictors\n\n-   Interaction terms\n\n-   Polynomial terms\n\nAll three topics are examples of feature engineering: building new input variables from existing ones to capture relationships that a raw linear model would miss. Despite these enrichments, the model remains linear in its coefficients, so everything we have learned so far still applies.\n\nWe'll be using three datasets to demonstrate concepts: the Beerwings dataset, the advertising dataset, and the mtcars dataset which is built into R.\n\n## Qualitative Predictors\n\nThe Beerwings dataset introduced at the end of Module 1.3 contains information on gender, hotwings and beer consumption for 30 patrons of a Minneapolis bar.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.5.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.2     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\ndf_url=\"https://raw.githubusercontent.com/jmayberr/math133-stat-learning-fall2026/refs/heads/main/Datasets/Beerwings.csv\"\nbeerwings=read.csv(df_url) |>\n  select(-ID)\nhead(beerwings)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Hotwings Beer Gender\n1        4   24      F\n2        5    0      F\n3        5   12      F\n4        6   12      F\n5        7   12      F\n6        7   12      F\n```\n\n\n:::\n:::\n\n\n\nIn the practice problem, you were asked to fit a SLM\n\n$$\nBeer = \\beta_0 + \\beta_1 \\times Wings + \\varepsilon\n$$\n\nWe also might want to look at the relationship between Gender and Beer consumption by considering a model of the form\n\n$$\nBeer = \\beta_0 + \\beta_1 \\times Gender + \\varepsilon\n$$\n\nas it seems there is definitely a difference in beer consumption between the two groups:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeerwings |>\n  ggplot(aes(x=Gender,y=Beer,fill=Gender))+\n  geom_boxplot(width=0.5)+\n  scale_fill_manual(values=c(\"#0072B2\",\"#D55E00\"))+\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](notes02_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\nThe standard way of incorporating *qualitative* or *categorical* variables like Gender into statistical models is via a process called *one-hot encoding*. If the variable is binary[^1], we choose one value to serve as the baseline for the model (R does this by alphabetical order so it will choose \"F\" in this example). The baseline value is *recoded* with a 0, and the other value with 1. In other words, we would define a new variable $$\nGenderM = \\begin{cases}1 & \\text{if  Gender == \"Male\"} \\\\ 0 & \\text{if  Gender == \"Female\"} \\end{cases}\n$$\n\n[^1]: Not to imply that Gender is binary, but there were only two values recorded in this dataset. It was Minnesota in the early 2000s.\n\nand then add this as a predictor in our SLM. We can *engineer* such variables in R using `ifelse`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeerwings$GenderM = ifelse(beerwings$Gender==\"M\",1,0)\ntable(beerwings$Gender,beerwings$GenderM)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   \n     0  1\n  F 15  0\n  M  0 15\n```\n\n\n:::\n:::\n\n\n\nThen we run `lm` with the new variable\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_lm=lm(Beer ~ GenderM,beerwings)\nsummary(fit_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Beer ~ GenderM, data = beerwings)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -30.4   -6.4    2.0    7.4   17.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   22.000      2.902   7.580 2.95e-08 ***\nGenderM        8.400      4.104   2.047   0.0502 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 11.24 on 28 degrees of freedom\nMultiple R-squared:  0.1301,\tAdjusted R-squared:  0.09906 \nF-statistic: 4.189 on 1 and 28 DF,  p-value: 0.05019\n```\n\n\n:::\n:::\n\n\n\nTo interpret this, males (GenderM =1) consumed about 8.4 more wings on average than females (GenderM=0) although the result was only moderately significant[^2] (p-value = 0.0502)\n\n[^2]: The hypothesis test for nonzero slope is essentially equivalent to doing a two-sample t-test for comparing average beer consumption between genders except that the degrees of freedom is different.\n\nEngineering a new variable through one-hot encoding was intentionally tedious to illustrate the steps involved. In the future, we'll just have R do it automatically within the `lm` call:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(Beer ~ Gender,beerwings)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Beer ~ Gender, data = beerwings)\n\nCoefficients:\n(Intercept)      GenderM  \n       22.0          8.4  \n```\n\n\n:::\n:::\n\n\n\nNotice that it adds \"M\" at the end of Gender to tell us which value is treated as a \"1\" in the encoding. You can directly use such calls in the future.\n\nFor qualitative predictors with $k \\geq 2$ categories, the idea is similar. We choose one category to serve as baseline and then we create $k-1$ binary variables for the other categories of the form $$\nX_j = \\begin{cases}1 & \\text{if  Category ==} j \\\\ 0 & \\text{if  Category !=} j\\end{cases}\n$$\n\nNote that `!=` is R language for \"not equal to\". The $X_j$ are called *indicator* or (group) *dummy* variables. Again, `lm` is built to handle this kind of stuff. Let's illustrate using the Math 37 survey dataset from the Module 1 Assessment\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_url=\"https://raw.githubusercontent.com/jmayberr/math133-stat-learning-fall2026/refs/heads/main/Datasets/survey_fall2025.csv\"\nsurvey=read.csv(df_url)\nhead(survey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  stress_score assessment_preference screen_time steps\n1           13            Term Paper           1  3000\n2           17               Exam(s)           6  3184\n3           16     Portfolio of Work           7  4412\n4            4        Course Project           6 10000\n5            4        Course Project           6 10000\n6            9            Term Paper           5  9300\n  marijuana_product_consumption honor_code_violation fastest_speed\n1                            No                   No            70\n2                            No                   No            60\n3                            No                   No            70\n4                           Yes                   No            97\n5                           Yes                  Yes            97\n6                            No                   No            90\n  maximum_alcohol_consumed         protest camp         investor_type exercise\n1                        0 Limited Protest  Yes          Conservative       20\n2                        0     Any Protest   No Moderately Aggressive        0\n3                        0 Limited Protest  Yes              Moderate       30\n4                        5 Limited Protest   No Moderately Aggressive      240\n5                        5 Limited Protest   No Moderately Aggressive      240\n6                        4 Limited Protest  Yes Moderately Aggressive       80\n  travel_time                                       race_ethnicity\n1          10                            Asian or Pacific Islander\n2          12                                   Hispanic or Latin@\n3           5                            Asian or Pacific Islander\n4          10 Asian or Pacific Islander;White, non Hispanic/Latin@\n5          12 Asian or Pacific Islander;White, non Hispanic/Latin@\n6          15                                   Hispanic or Latin@\n  biological_sex athlete home_environment age  gpa   school units   urm   api\n1         Female      No         Suburban  20 3.40    SOECS    18 FALSE  TRUE\n2         Female      No            Urban  18 3.16    SOECS    14  TRUE FALSE\n3         Female      HS         Suburban  19 4.00 COP (NS)    17 FALSE  TRUE\n4           Male College         Suburban  19 2.88      ESB    16  TRUE  TRUE\n5           Male College         Suburban  19 2.88      ESB    16  TRUE  TRUE\n6         Female      HS         Suburban  19 3.00      ESB    16  TRUE FALSE\n  multiracial number_of_fears snake_fear spider_fear rodent_fear dentist_fear\n1       FALSE              12       TRUE        TRUE        TRUE        FALSE\n2       FALSE              11       TRUE        TRUE        TRUE        FALSE\n3       FALSE               5      FALSE        TRUE       FALSE        FALSE\n4        TRUE               1      FALSE        TRUE       FALSE        FALSE\n5        TRUE               1      FALSE        TRUE       FALSE        FALSE\n6       FALSE              11      FALSE        TRUE        TRUE        FALSE\n  height_fear blood_fear enclosed_fear speaking_fear darkness_fear failure_fear\n1        TRUE       TRUE          TRUE         FALSE          TRUE         TRUE\n2        TRUE      FALSE         FALSE          TRUE          TRUE         TRUE\n3       FALSE      FALSE          TRUE         FALSE          TRUE         TRUE\n4       FALSE      FALSE         FALSE         FALSE         FALSE        FALSE\n5       FALSE      FALSE         FALSE         FALSE         FALSE        FALSE\n6        TRUE       TRUE          TRUE         FALSE          TRUE         TRUE\n  ridicule_fear rejection_fear commitment_fear intimacy_fears death_fear\n1          TRUE           TRUE           FALSE          FALSE       TRUE\n2          TRUE           TRUE           FALSE          FALSE       TRUE\n3         FALSE          FALSE           FALSE          FALSE      FALSE\n4         FALSE          FALSE           FALSE          FALSE      FALSE\n5         FALSE          FALSE           FALSE          FALSE      FALSE\n6          TRUE           TRUE           FALSE          FALSE       TRUE\n```\n\n\n:::\n:::\n\n\n\nSuppose we want to look at the relationship between *home_environment* (rural, suburban, or urban) and *stress_score.* We can run an SLM:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_lm=lm(stress_score~home_environment,survey)\nsummary(fit_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = stress_score ~ home_environment, data = survey)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.5542  -5.5542   0.0503   4.4309  15.4458 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                21.286      2.633   8.085 3.64e-13 ***\nhome_environmentSuburban   -4.731      2.742  -1.726   0.0867 .  \nhome_environmentUrban      -3.672      2.835  -1.295   0.1974    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.966 on 131 degrees of freedom\nMultiple R-squared:  0.02435,\tAdjusted R-squared:  0.009456 \nF-statistic: 1.635 on 2 and 131 DF,  p-value: 0.1989\n```\n\n\n:::\n:::\n\n\n\nNotice that the output now shows two coefficients even though we only had one input variable. That is because both Suburban and Urban are being compared with the baseline of Rural. The coefficients say that Suburban and Urban students, respectively, are expected to have stress scores of $4.731$ and $3.672$ lower than Rural students although only Suburban had a moderately significant difference with Rural.\n\nOne disadvantage of one-hot encoding this way is that we can't compare Suburban and Urban directly. To do so, we nee to recode *home_environment* so that Suburban comes first^[You can also set up contrasts between categories which allow you to interpret coefficients relative to the overall mean. Look up the documentation of `contrasts` for details.]:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey$home_environment <- relevel(factor(survey$home_environment), \n                                   ref = \"Suburban\")\ntable(survey$home_environment)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSuburban    Rural    Urban \n      83        7       44 \n```\n\n\n:::\n:::\n\n\n\nRerunning `lm` will now use Suburban as the baseline.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_lm=lm(stress_score~home_environment,survey)\nsummary(fit_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = stress_score ~ home_environment, data = survey)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.5542  -5.5542   0.0503   4.4309  15.4458 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            16.5542     0.7646  21.651   <2e-16 ***\nhome_environmentRural   4.7315     2.7416   1.726   0.0867 .  \nhome_environmentUrban   1.0594     1.2990   0.816   0.4162    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.966 on 131 degrees of freedom\nMultiple R-squared:  0.02435,\tAdjusted R-squared:  0.009456 \nF-statistic: 1.635 on 2 and 131 DF,  p-value: 0.1989\n```\n\n\n:::\n:::\n\n\n\n## Interaction Terms\n\nReturning to our Beerwings example, suppose we want to jointly look at the impact of Gender and Hotwings on Beer consumption:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeerwings |>\n  ggplot(aes(x=Hotwings,y=Beer,color=Gender))+\n  geom_point(shape=1)+\n  scale_color_manual(values=c(\"#0072B2\",\"#D55E00\"))+\n  geom_smooth(method=lm,se=F)+\n  theme_classic()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](notes02_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\nThere are two separate questions we could ask\n\n1.  Do the two lines have the same intercept?\n2.  Do the two lines have the same slope?\n\nThe first can be answered by considering a multiple regression model of the form\n\n$$\nBeer = \\beta_0 + \\beta_1 \\times Gender + \\beta_2 \\times Hotwings + \\varepsilon\n$$\n\nThe $\\beta_1$ serves as the \"shift\" in intercept between Gender = 0 (F) and Gender = 1 (M) because if Gender = 0 we get\n\n$$\nBeer = \\beta_0  + \\beta_2 \\times Hotwings + \\varepsilon\n$$ and if Gender = 1, we get\n\n$$\nBeer = (\\beta_0 + \\beta_1)  + \\beta_2 \\times Hotwings + \\varepsilon\n$$\n\nso $\\beta_1$ is the difference in intercepts. This is just another application of multiple regression\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_lm=lm(Beer~Gender+Hotwings,beerwings)\nsummary(fit_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Beer ~ Gender + Hotwings, data = beerwings)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-16.7854  -5.0496   0.7114   2.7953  18.7114 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   2.5506     3.8125   0.669    0.509    \nGenderM      -2.4361     3.3042  -0.737    0.467    \nHotwings      2.0839     0.3512   5.934 2.52e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.541 on 27 degrees of freedom\nMultiple R-squared:  0.6224,\tAdjusted R-squared:  0.5945 \nF-statistic: 22.26 on 2 and 27 DF,  p-value: 1.946e-06\n```\n\n\n:::\n:::\n\n\n\nNote that the coefficient of GenderM was not significant (although interestingly, it was negative!) so we conclude that the intercepts for Male and Female were not significantly different. To test for a difference in slopes, we can add an *interaction term* and consider the model\n\n$$\nBeer = \\beta_0 + \\beta_1 (Gender) + \\beta_2 (Hotwings) + \\beta_3 (Gender \\times Hotwings)+  \\varepsilon\n$$\n\nTo see why this works, note that if Gender = 0, the model becomes $$\nBeer = \\beta_0 + \\beta_2 (Hotwings)+  \\varepsilon\n$$ while if Gender = 1, we get $$\nBeer = \\beta_0 + \\beta_1 + (\\beta_2+\\beta_3)  (Hotwings)+  \\varepsilon\n$$\n\nSo $\\beta_3$ is the difference in the slopes and $\\beta_1$ is still the difference in the intercepts.\n\nAdding an interaction term is the same as engineering a new variable whose values are $Hotwings \\times Gender$, but again `lm` will do this automatically if you include both variables with a `*` between them:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_lm_int=lm(Beer~Gender*Hotwings,beerwings)\nsummary(fit_lm_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Beer ~ Gender * Hotwings, data = beerwings)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-17.7632  -4.5789   0.6316   2.7716  18.6316 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        0.3158     5.7089   0.055 0.956310    \nGenderM            1.9737     8.9429   0.221 0.827051    \nHotwings           2.3233     0.5740   4.048 0.000413 ***\nGenderM:Hotwings  -0.3891     0.7317  -0.532 0.599379    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.643 on 26 degrees of freedom\nMultiple R-squared:  0.6265,\tAdjusted R-squared:  0.5834 \nF-statistic: 14.54 on 3 and 26 DF,  p-value: 9.304e-06\n```\n\n\n:::\n:::\n\n\n\nIn this case, the coefficient of *GenderM:Hotwings* tells us the estimate of $\\beta_3$. In this case it is negative, but insignificant so we conclude that gender does not impact beer consumption after accounting for wings consumption (i.e. if you have two people consume the same number of wings, our model would predict the same beer consumption regardless of gender).\n\nWe can also include interactions between numeric predictors like in the advertising dataset. Remember that 3D plot we showed in Module 2.1 and my comment about wanting to peal down the surface? Well we can do that if we consider the model $$\nsales = \\beta_0 + \\beta_1 (TV) + \\beta_2 (radio) + \\beta_3 (TV \\times radio) + \\varepsilon\n$$\n\nwhich creates an estimation function of the form $$\n\\hat y = a + b_1 x_1 + b_2 x_2 + b_3 x_1x_2\n$$\n\nIt turns out the interaction between TV and radio is significant:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_url=\"https://raw.githubusercontent.com/jmayberr/math133-stat-learning-fall2026/refs/heads/main/Datasets/Advertising.csv\"\nadvertising=read.csv(df_url)\nsales_lm_int=lm(sales~TV*radio,data=advertising)\nsummary(sales_lm_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sales ~ TV * radio, data = advertising)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.3366 -0.4028  0.1831  0.5948  1.5246 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 6.750e+00  2.479e-01  27.233   <2e-16 ***\nTV          1.910e-02  1.504e-03  12.699   <2e-16 ***\nradio       2.886e-02  8.905e-03   3.241   0.0014 ** \nTV:radio    1.086e-03  5.242e-05  20.727   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9435 on 196 degrees of freedom\nMultiple R-squared:  0.9678,\tAdjusted R-squared:  0.9673 \nF-statistic:  1963 on 3 and 196 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nEven more rewarding is to re-examine the 3D plot with this new model:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(plotly)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'plotly' was built under R version 4.5.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'plotly'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:ggplot2':\n\n    last_plot\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:stats':\n\n    filter\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:graphics':\n\n    layout\n```\n\n\n:::\n\n```{.r .cell-code}\nx_values=seq(0,300, by=10)\ny_values=seq(0,50,by=5)\nxy_grid=expand.grid(TV=x_values,radio=y_values)\nyhat=matrix(predict(sales_lm_int,xy_grid),\n         nrow=length(x_values),ncol=length(y_values))\nadv_3d=plot_ly(advertising,x=~TV,y=~radio,z=~sales)\nadv_3d |> \n  add_markers(marker = list(color = \"black\", size = 3)) |>\n  add_surface(x = ~x_values, \n              y = ~y_values, \n              z = ~t(yhat),\n              colorscale = \"Viridis\",\n              opacity = 0.7) |>\n  layout(scene = list(\n    xaxis = list(title = \"TV\"),\n    yaxis = list(title = \"Radio\"),\n    zaxis = list(title = \"Sales\")\n  ))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-fc1f994e6e08fcc989c5\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-fc1f994e6e08fcc989c5\">{\"x\":{\"visdat\":{\"53548ef1cc3\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"53548ef1cc3\",\"attrs\":{\"53548ef1cc3\":{\"x\":{},\"y\":{},\"z\":{},\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"black\",\"size\":3},\"inherit\":true},\"53548ef1cc3.1\":{\"x\":{},\"y\":{},\"z\":{},\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"surface\",\"colorscale\":\"Viridis\",\"opacity\":0.69999999999999996,\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"xaxis\":{\"title\":\"TV\"},\"yaxis\":{\"title\":\"Radio\"},\"zaxis\":{\"title\":\"Sales\"}},\"hovermode\":\"closest\",\"showlegend\":false,\"legend\":{\"yanchor\":\"top\",\"y\":0.5}},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[230.09999999999999,44.5,17.199999999999999,151.5,180.80000000000001,8.6999999999999993,57.5,120.2,8.5999999999999996,199.80000000000001,66.099999999999994,214.69999999999999,23.800000000000001,97.5,204.09999999999999,195.40000000000001,67.799999999999997,281.39999999999998,69.200000000000003,147.30000000000001,218.40000000000001,237.40000000000001,13.199999999999999,228.30000000000001,62.299999999999997,262.89999999999998,142.90000000000001,240.09999999999999,248.80000000000001,70.599999999999994,292.89999999999998,112.90000000000001,97.200000000000003,265.60000000000002,95.700000000000003,290.69999999999999,266.89999999999998,74.700000000000003,43.100000000000001,228,202.5,177,293.60000000000002,206.90000000000001,25.100000000000001,175.09999999999999,89.700000000000003,239.90000000000001,227.19999999999999,66.900000000000006,199.80000000000001,100.40000000000001,216.40000000000001,182.59999999999999,262.69999999999999,198.90000000000001,7.2999999999999998,136.19999999999999,210.80000000000001,210.69999999999999,53.5,261.30000000000001,239.30000000000001,102.7,131.09999999999999,69,31.5,139.30000000000001,237.40000000000001,216.80000000000001,199.09999999999999,109.8,26.800000000000001,129.40000000000001,213.40000000000001,16.899999999999999,27.5,120.5,5.4000000000000004,116,76.400000000000006,239.80000000000001,75.299999999999997,68.400000000000006,213.5,193.19999999999999,76.299999999999997,110.7,88.299999999999997,109.8,134.30000000000001,28.600000000000001,217.69999999999999,250.90000000000001,107.40000000000001,163.30000000000001,197.59999999999999,184.90000000000001,289.69999999999999,135.19999999999999,222.40000000000001,296.39999999999998,280.19999999999999,187.90000000000001,238.19999999999999,137.90000000000001,25,90.400000000000006,13.1,255.40000000000001,225.80000000000001,241.69999999999999,175.69999999999999,209.59999999999999,78.200000000000003,75.099999999999994,139.19999999999999,76.400000000000006,125.7,19.399999999999999,141.30000000000001,18.800000000000001,224,123.09999999999999,229.5,87.200000000000003,7.7999999999999998,80.200000000000003,220.30000000000001,59.600000000000001,0.69999999999999996,265.19999999999999,8.4000000000000004,219.80000000000001,36.899999999999999,48.299999999999997,25.600000000000001,273.69999999999999,43,184.90000000000001,73.400000000000006,193.69999999999999,220.5,104.59999999999999,96.200000000000003,140.30000000000001,240.09999999999999,243.19999999999999,38,44.700000000000003,280.69999999999999,121,197.59999999999999,171.30000000000001,187.80000000000001,4.0999999999999996,93.900000000000006,149.80000000000001,11.699999999999999,131.69999999999999,172.5,85.700000000000003,188.40000000000001,163.5,117.2,234.5,17.899999999999999,206.80000000000001,215.40000000000001,284.30000000000001,50,164.5,19.600000000000001,168.40000000000001,222.40000000000001,276.89999999999998,248.40000000000001,170.19999999999999,276.69999999999999,165.59999999999999,156.59999999999999,218.5,56.200000000000003,287.60000000000002,253.80000000000001,205,139.5,191.09999999999999,286,18.699999999999999,39.5,75.5,17.199999999999999,166.80000000000001,149.69999999999999,38.200000000000003,94.200000000000003,177,283.60000000000002,232.09999999999999],\"y\":[37.799999999999997,39.299999999999997,45.899999999999999,41.299999999999997,10.800000000000001,48.899999999999999,32.799999999999997,19.600000000000001,2.1000000000000001,2.6000000000000001,5.7999999999999998,24,35.100000000000001,7.5999999999999996,32.899999999999999,47.700000000000003,36.600000000000001,39.600000000000001,20.5,23.899999999999999,27.699999999999999,5.0999999999999996,15.9,16.899999999999999,12.6,3.5,29.300000000000001,16.699999999999999,27.100000000000001,16,28.300000000000001,17.399999999999999,1.5,20,1.3999999999999999,4.0999999999999996,43.799999999999997,49.399999999999999,26.699999999999999,37.700000000000003,22.300000000000001,33.399999999999999,27.699999999999999,8.4000000000000004,25.699999999999999,22.5,9.9000000000000004,41.5,15.800000000000001,11.699999999999999,3.1000000000000001,9.5999999999999996,41.700000000000003,46.200000000000003,28.800000000000001,49.399999999999999,28.100000000000001,19.199999999999999,49.600000000000001,29.5,2,42.700000000000003,15.5,29.600000000000001,42.799999999999997,9.3000000000000007,24.600000000000001,14.5,27.5,43.899999999999999,30.600000000000001,14.300000000000001,33,5.7000000000000002,24.600000000000001,43.700000000000003,1.6000000000000001,28.5,29.899999999999999,7.7000000000000002,26.699999999999999,4.0999999999999996,20.300000000000001,44.5,43,18.399999999999999,27.5,40.600000000000001,25.5,47.799999999999997,4.9000000000000004,1.5,33.5,36.5,14,31.600000000000001,3.5,21,42.299999999999997,41.700000000000003,4.2999999999999998,36.299999999999997,10.1,17.199999999999999,34.299999999999997,46.399999999999999,11,0.29999999999999999,0.40000000000000002,26.899999999999999,8.1999999999999993,38,15.4,20.600000000000001,46.799999999999997,35,14.300000000000001,0.80000000000000004,36.899999999999999,16,26.800000000000001,21.699999999999999,2.3999999999999999,34.600000000000001,32.299999999999997,11.800000000000001,38.899999999999999,0,49,12,39.600000000000001,2.8999999999999999,27.199999999999999,33.5,38.600000000000001,47,39,28.899999999999999,25.899999999999999,43.899999999999999,17,35.399999999999999,33.200000000000003,5.7000000000000002,14.800000000000001,1.8999999999999999,7.2999999999999998,49,40.299999999999997,25.800000000000001,13.9,8.4000000000000004,23.300000000000001,39.700000000000003,21.100000000000001,11.6,43.5,1.3,36.899999999999999,18.399999999999999,18.100000000000001,35.799999999999997,18.100000000000001,36.799999999999997,14.699999999999999,3.3999999999999999,37.600000000000001,5.2000000000000002,23.600000000000001,10.6,11.6,20.899999999999999,20.100000000000001,7.0999999999999996,3.3999999999999999,48.899999999999999,30.199999999999999,7.7999999999999998,2.2999999999999998,10,2.6000000000000001,5.4000000000000004,5.7000000000000002,43,21.300000000000001,45.100000000000001,2.1000000000000001,28.699999999999999,13.9,12.1,41.100000000000001,10.800000000000001,4.0999999999999996,42,35.600000000000001,3.7000000000000002,4.9000000000000004,9.3000000000000007,42,8.5999999999999996],\"z\":[22.100000000000001,10.4,9.3000000000000007,18.5,12.9,7.2000000000000002,11.800000000000001,13.199999999999999,4.7999999999999998,10.6,8.5999999999999996,17.399999999999999,9.1999999999999993,9.6999999999999993,19,22.399999999999999,12.5,24.399999999999999,11.300000000000001,14.6,18,12.5,5.5999999999999996,15.5,9.6999999999999993,12,15,15.9,18.899999999999999,10.5,21.399999999999999,11.9,9.5999999999999996,17.399999999999999,9.5,12.800000000000001,25.399999999999999,14.699999999999999,10.1,21.5,16.600000000000001,17.100000000000001,20.699999999999999,12.9,8.5,14.9,10.6,23.199999999999999,14.800000000000001,9.6999999999999993,11.4,10.699999999999999,22.600000000000001,21.199999999999999,20.199999999999999,23.699999999999999,5.5,13.199999999999999,23.800000000000001,18.399999999999999,8.0999999999999996,24.199999999999999,15.699999999999999,14,18,9.3000000000000007,9.5,13.4,18.899999999999999,22.300000000000001,18.300000000000001,12.4,8.8000000000000007,11,17,8.6999999999999993,6.9000000000000004,14.199999999999999,5.2999999999999998,11,11.800000000000001,12.300000000000001,11.300000000000001,13.6,21.699999999999999,15.199999999999999,12,16,12.9,16.699999999999999,11.199999999999999,7.2999999999999998,19.399999999999999,22.199999999999999,11.5,16.899999999999999,11.699999999999999,15.5,25.399999999999999,17.199999999999999,11.699999999999999,23.800000000000001,14.800000000000001,14.699999999999999,20.699999999999999,19.199999999999999,7.2000000000000002,8.6999999999999993,5.2999999999999998,19.800000000000001,13.4,21.800000000000001,14.1,15.9,14.6,12.6,12.199999999999999,9.4000000000000004,15.9,6.5999999999999996,15.5,7,11.6,15.199999999999999,19.699999999999999,10.6,6.5999999999999996,8.8000000000000007,24.699999999999999,9.6999999999999993,1.6000000000000001,12.699999999999999,5.7000000000000002,19.600000000000001,10.800000000000001,11.6,9.5,20.800000000000001,9.5999999999999996,20.699999999999999,10.9,19.199999999999999,20.100000000000001,10.4,11.4,10.300000000000001,13.199999999999999,25.399999999999999,10.9,10.1,16.100000000000001,11.6,16.600000000000001,19,15.6,3.2000000000000002,15.300000000000001,10.1,7.2999999999999998,12.9,14.4,13.300000000000001,14.9,18,11.9,11.9,8,12.199999999999999,17.100000000000001,15,8.4000000000000004,14.5,7.5999999999999996,11.699999999999999,11.5,27,20.199999999999999,11.699999999999999,11.800000000000001,12.6,10.5,12.199999999999999,8.6999999999999993,26.199999999999999,17.600000000000001,22.600000000000001,10.300000000000001,17.300000000000001,15.9,6.7000000000000002,10.800000000000001,9.9000000000000004,5.9000000000000004,19.600000000000001,17.300000000000001,7.5999999999999996,9.6999999999999993,12.800000000000001,25.5,13.4],\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"black\",\"size\":3,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"colorbar\":{\"title\":\"sales<br />t(yhat)\",\"ticklen\":2,\"len\":0.5,\"lenmode\":\"fraction\",\"y\":1,\"yanchor\":\"top\"},\"colorscale\":\"Viridis\",\"showscale\":true,\"x\":[0,10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200,210,220,230,240,250,260,270,280,290,300],\"y\":[0,5,10,15,20,25,30,35,40,45,50],\"z\":[[6.7502202030751404,6.9412309413855704,7.1322416796960004,7.3232524180064305,7.5142631563168614,7.7052738946272914,7.8962846329377214,8.0872953712481515,8.2783061095585815,8.4693168478690115,8.6603275861794415,8.8513383244898716,9.0423490628003016,9.2333598011107334,9.4243705394211617,9.6153812777315935,9.8063920160420217,9.9974027543524535,10.188413492662884,10.379424230973314,10.570434969283744,10.761445707594174,10.952456445904604,11.143467184215034,11.334477922525464,11.525488660835894,11.716499399146326,11.907510137456754,12.098520875767186,12.289531614077614,12.480542352388046],[6.8945219025747644,7.1398573757846924,7.3851928489946204,7.6305283222045484,7.8758637954144772,8.1211992686244052,8.3665347418343323,8.6118702150442612,8.8572056882541883,9.1025411614641172,9.3478766346740443,9.5932121078839732,9.838547581093902,10.083883054303831,10.329218527513758,10.574554000723687,10.819889473933614,11.065224947143543,11.310560420353472,11.555895893563399,11.801231366773328,12.046566839983255,12.291902313193184,12.537237786403111,12.78257325961304,13.027908732822969,13.273244206032897,13.518579679242825,13.763915152452753,14.009250625662681,14.254586098872609],[7.0388236020743884,7.3384838101838143,7.6381440182932403,7.9378042264026671,8.2374644345120931,8.537124642621519,8.8367848507309468,9.1364450588403727,9.4361052669497987,9.7357654750592246,10.035425683168651,10.335085891278077,10.634746099387502,10.93440630749693,11.234066515606354,11.533726723715782,11.833386931825206,12.133047139934634,12.432707348044062,12.732367556153488,13.032027764262914,13.33168797237234,13.631348180481766,13.931008388591192,14.230668596700617,14.530328804810043,14.829989012919471,15.129649221028895,15.429309429138323,15.728969637247747,16.028629845357177],[7.1831253015740124,7.5371102445829363,7.8910951875918602,8.245080130600785,8.5990650736097098,8.9530500166186329,9.3070349596275577,9.6610199026364807,10.015004845645405,10.36898978865433,10.722974731663253,11.076959674672178,11.430944617681103,11.784929560690028,12.138914503698951,12.492899446707876,12.846884389716799,13.200869332725723,13.554854275734648,13.908839218743573,14.262824161752498,14.616809104761421,14.970794047770346,15.324778990779269,15.678763933788193,16.032748876797118,16.386733819806043,16.740718762814964,17.094703705823893,17.448688648832814,17.802673591841739],[7.3274270010736355,7.7357366789820574,8.1440463568904793,8.5523560347989012,8.9606657127073266,9.3689753906157485,9.7772850685241703,10.185594746432592,10.593904424341014,11.002214102249436,11.41052378015786,11.818833458066281,12.227143135974703,12.635452813883127,13.043762491791547,13.452072169699971,13.860381847608391,14.268691525516816,14.677001203425238,15.08531088133366,15.493620559242082,15.901930237150506,16.310239915058926,16.718549592967349,17.126859270875769,17.535168948784193,17.943478626692617,18.351788304601037,18.76009798250946,19.168407660417881,19.576717338326304],[7.4717287005732596,7.9343631133811794,8.3969975261891001,8.8596319389970208,9.3222663518049416,9.7849007646128605,10.247535177420781,10.710169590228702,11.172804003036621,11.635438415844542,12.098072828652462,12.560707241460383,13.023341654268304,13.485976067076225,13.948610479884143,14.411244892692064,14.873879305499983,15.336513718307906,15.799148131115825,16.261782543923747,16.724416956731666,17.187051369539585,17.649685782347508,18.112320195155426,18.574954607963349,19.037589020771268,19.500223433579187,19.962857846387109,20.425492259195028,20.888126672002947,21.35076108481087],[7.6160304000728836,8.1329895477803014,8.6499486954877192,9.1669078431951387,9.6838669909025583,10.200826138609976,10.717785286317394,11.234744434024813,11.751703581732231,12.268662729439649,12.785621877147069,13.302581024854486,13.819540172561904,14.336499320269324,14.85345846797674,15.370417615684161,15.887376763391577,16.404335911098997,16.921295058806415,17.438254206513832,17.95521335422125,18.472172501928668,18.989131649636089,19.506090797343507,20.023049945050925,20.540009092758343,21.056968240465764,21.573927388173182,22.0908865358806,22.607845683588017,23.124804831295435],[7.7603320995725076,8.3316159821794233,8.9028998647863418,9.4741837473932566,10.045467630000173,10.61675151260709,11.188035395214007,11.759319277820921,12.330603160427838,12.901887043034755,13.473170925641671,14.044454808248588,14.615738690855505,15.187022573462421,15.758306456069336,16.329590338676255,16.900874221283168,17.472158103890088,18.043441986497001,18.614725869103921,19.186009751710834,19.757293634317751,20.328577516924668,20.899861399531584,21.471145282138501,22.042429164745418,22.613713047352334,23.184996929959247,23.756280812566168,24.327564695173081,24.898848577780001],[7.9046337990721316,8.5302424165785453,9.1558510340849608,9.7814596515913745,10.40706826909779,11.032676886604204,11.658285504110619,12.283894121617031,12.909502739123447,13.53511135662986,14.160719974136276,14.78632859164269,15.411937209149105,16.037545826655521,16.663154444161933,17.288763061668348,17.914371679174764,18.539980296681179,19.165588914187591,19.791197531694007,20.416806149200418,21.042414766706834,21.668023384213249,22.293632001719665,22.919240619226077,23.544849236732492,24.170457854238908,24.79606647174532,25.421675089251735,26.047283706758151,26.672892324264566],[8.0489354985717547,8.7288688509776691,9.4088022033835799,10.088735555789494,10.768668908195405,11.448602260601318,12.12853561300723,12.808468965413143,13.488402317819055,14.168335670224968,14.84826902263088,15.528202375036791,16.208135727442706,16.88806907984862,17.568002432254531,18.247935784660442,18.927869137066352,19.60780248947227,20.287735841878181,20.967669194284092,21.647602546690003,22.327535899095917,23.007469251501831,23.687402603907742,24.367335956313653,25.047269308719567,25.727202661125482,26.407136013531392,27.087069365937303,27.767002718343214,28.446936070749132],[8.1932371980713796,8.9274952853767893,9.6617533726822007,10.39601145998761,11.130269547293022,11.864527634598431,12.598785721903841,13.333043809209252,14.067301896514662,14.801559983820074,15.535818071125483,16.270076158430893,17.004334245736302,17.738592333041716,18.472850420347125,19.207108507652535,19.941366594957945,20.675624682263358,21.409882769568767,22.144140856874181,22.878398944179587,23.612657031485,24.34691511879041,25.081173206095819,25.815431293401232,26.549689380706639,27.283947468012052,28.018205555317461,28.752463642622871,29.486721729928284,30.220979817233694]],\"type\":\"surface\",\"opacity\":0.69999999999999996,\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\nIts so beautiful it brings tears to my eyes.\n\nA second way of visualizing the interactive effect of TV and radio is to compare the slopes of the regression lines for sales vs TV when radio is high vs low. First, we need to engineer a new variable to represent the latter splitting which we will base on the median\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmr=median(advertising$radio)\nadvertising$radio_level=ifelse(advertising$radio>mr,\"high\",\"low\")\nadvertising |>\n  ggplot(aes(x=TV,y=sales,color=radio_level))+\n  geom_point()+\n  geom_smooth(method=\"lm\",se=FALSE)+\n  scale_color_manual(values=c(\"darkorange\",\"#17806d\"))\n```\n\n::: {.cell-output-display}\n![](notes02_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\nYou can see that unlike in the beerwings example, the slopes of the regression lines are different for the two groups: when radio spending is high, you also get more \"bang for your buck\" in terms of TV spending too (higher slope). This is the reason an interactive effect is also sometimes called a *synergy effect* (at least when the coefficient is positive).\n\n## Polynomial Terms\n\nThe final type of enrichment we'll discuss in this section is the addition of polynomial terms in linear models[^3]. To motivate this, lets look at the `mtcars` dataset which is built into R and has specs on 30 different makes of cars:\n\n[^3]: It may seem strange to call polynomial models linear, but as you can see below, they are linear in the coefficients $\\beta_i$. The nonlinearity only creates additional features to engineer.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mtcars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 32\nColumns: 11\n$ mpg  <dbl> 21.0, 21.0, 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 22.8, 19.2, 17.8,…\n$ cyl  <dbl> 6, 6, 4, 6, 8, 6, 8, 4, 4, 6, 6, 8, 8, 8, 8, 8, 8, 4, 4, 4, 4, 8,…\n$ disp <dbl> 160.0, 160.0, 108.0, 258.0, 360.0, 225.0, 360.0, 146.7, 140.8, 16…\n$ hp   <dbl> 110, 110, 93, 110, 175, 105, 245, 62, 95, 123, 123, 180, 180, 180…\n$ drat <dbl> 3.90, 3.90, 3.85, 3.08, 3.15, 2.76, 3.21, 3.69, 3.92, 3.92, 3.92,…\n$ wt   <dbl> 2.620, 2.875, 2.320, 3.215, 3.440, 3.460, 3.570, 3.190, 3.150, 3.…\n$ qsec <dbl> 16.46, 17.02, 18.61, 19.44, 17.02, 20.22, 15.84, 20.00, 22.90, 18…\n$ vs   <dbl> 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,…\n$ am   <dbl> 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,…\n$ gear <dbl> 4, 4, 4, 3, 3, 3, 3, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3,…\n$ carb <dbl> 4, 4, 1, 1, 2, 1, 4, 2, 2, 4, 4, 3, 3, 3, 4, 4, 4, 1, 2, 1, 1, 2,…\n```\n\n\n:::\n:::\n\n\n\nYou may not know much about cars (I sure don't!) but if you're driving one that takes gas, I'm sure you're paying lots of attention to the mpg column these days. Suppose we want to see how mpg depends on the horsepower (hp) of the car:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmtcars |> \n  ggplot(aes(x=hp,y=mpg))+\n  geom_point()+\n  geom_smooth(method=lm,\n              color=\"#D55E00\")\n```\n\n::: {.cell-output-display}\n![](notes02_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\nThis doesn't look very linear[^4] even though we get a significant linear coefficient and decent $R^2$ :\n\n[^4]: We'll further discuss checking for nonlinearity Module 2.3\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_lm=lm(mpg~hp,mtcars)\nsummary(fit_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mpg ~ hp, data = mtcars)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.7121 -2.1122 -0.8854  1.5819  8.2360 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 30.09886    1.63392  18.421  < 2e-16 ***\nhp          -0.06823    0.01012  -6.742 1.79e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.863 on 30 degrees of freedom\nMultiple R-squared:  0.6024,\tAdjusted R-squared:  0.5892 \nF-statistic: 45.46 on 1 and 30 DF,  p-value: 1.788e-07\n```\n\n\n:::\n:::\n\n\n\nInstead, noticing the curvature, let's try fitting a quadratic model\n\n$$\nmpg = \\beta_0 + \\beta_1 (hp) + \\beta_2 (hp)^2 + \\varepsilon\n$$\n\nThis requires engineering a new variable $(hp)^2$ which `lm` will do automatically:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_lm_quad=lm(mpg~hp+I(hp^2),mtcars)\nsummary(fit_lm_quad)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mpg ~ hp + I(hp^2), data = mtcars)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.5512 -1.6027 -0.6977  1.5509  8.7213 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  4.041e+01  2.741e+00  14.744 5.23e-15 ***\nhp          -2.133e-01  3.488e-02  -6.115 1.16e-06 ***\nI(hp^2)      4.208e-04  9.844e-05   4.275 0.000189 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.077 on 29 degrees of freedom\nMultiple R-squared:  0.7561,\tAdjusted R-squared:  0.7393 \nF-statistic: 44.95 on 2 and 29 DF,  p-value: 1.301e-09\n```\n\n\n:::\n:::\n\n\n\nWe see an improvement in $R^2$ and the model visually matches the data better too (although the increase in mpg for large hp is unrealistic):\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmtcars |> \n  ggplot(aes(x=hp,y=mpg))+\n  geom_point()+\n  geom_smooth(method=lm,\n              formula=y~poly(x,2),\n              color = \"#0072B2\")\n```\n\n::: {.cell-output-display}\n![](notes02_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\nTo get a more realistic model which incorporates curvature without the increase, we need to use a data transformation. This and a few other topics related to regression diagnostics will be discussed in 2.3.\n\n## Practice\n\nThe [credit](https://raw.githubusercontent.com/jmayberr/math133-stat-learning-fall2026/refs/heads/main/Datasets/credit.csv) dataset (Source: [ISLR](https://www.statlearning.com/)) contains simulated data on customer credit card balance based on several predictors including income, limit, rating, cards, age, education, own, student, married, and region.\n\n1.  Fit a multiple regression model using Income, Student, and Region. Which were significant?\n2.  Interpret the coefficient of the Student variable.\n3.  Interpret the coefficients of the region variables. What was the baseline?\n4.  Create a scatterplot and trendline of Balance vs Income with points colored by Student. Does it look like there is a difference in the intercepts or slopes of the lines?\n5.  Test for an interactive effect between Income and Student. Does the interaction improve the model?\n",
    "supporting": [
      "notes02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../site_libs/plotly-binding-4.12.0/plotly.js\"></script>\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/plotly-main-2.25.2/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}