{
  "hash": "2487c63319e8ab7b9387ef37b811fb5a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Module 2.3: Evaluating Classification Models\"\n---\n\n\n\n\n\n\n\n\n\n\n## Introduction\n\nIn these notes we'll be give a more detailed look at the framingham model from the practice problem at the end of the last notes. Please take some time to investigate it on your own first before ruining the surprise. \n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nframingham = read_csv(\"https://raw.githubusercontent.com/jmayberr/math133-stat-learning-fall2026/refs/heads/main/Datasets/framingham.csv\") |>\n  mutate(across(c(\"male\",\"currentSmoker\",\"BPMeds\",\"prevalentStroke\",\"prevalentHyp\"), as.factor)) |>\n  drop_na()\n\nchd_glm = glm(TenYearCHD ~ ., data = framingham, family = \"binomial\")\nsummary(chd_glm)\n```\n:::\n\n\n\n\n\n\n\n\nWe'll start off with a few additional words abotu interpreting coefficients and then proceed to enrich our understanding of \"accuracy\" by examining false positive vs false negatives, working towards a better metric of balanced accuracy and a more nuanced picture of how well our models fit classification data. \n\n## Interpreting Coefficients\n\nThe coefficients in a logistic regression model are on the log-odds scale, which makes them difficult to interpret directly. Exponentiating them gives us **odds ratios**, which are easier to describe\n\nFor example, we can ask: how much more likely are males to develop CHD compared to females? For this, we use the coefficient of \"male1\" from our model above and exponentiate the result \n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(coef(chd_glm)[\"male1\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   male1 \n1.742111 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nThis tells us that Males are about 1.74 as likely to get CHD as females if we hold all other variables constant. It is common to express this as a percentage by subtracting 1 from the above result and multiplying by 100:\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsprintf(\"The odds of getting CHD are %.0f%% higher for males compared to females\",\n        (exp(coef(chd_glm)[\"male1\"]) - 1) * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"The odds of getting CHD are 74% higher for males compared to females\"\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\nWe can also ask about the impact of reducing cigarette consumption. Suppose for example we want to know what happens if we reduce cigaratte consumption by 20 per day. This leads to teh following change in odds of developing CHD: \n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(-20 * coef(chd_glm)[\"cigsPerDay\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncigsPerDay \n 0.6986635 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\nNotice this time the answer is less than 1 so to express as a percentage, subtract the number from 1 and multiply by 100:\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsprintf(\"The odds of getting CHD decrease by %.0f%% if cigs per day decreases by 20\",\n        (1 - exp(-20 * coef(chd_glm)[\"cigsPerDay\"])) * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"The odds of getting CHD decrease by 30% if cigs per day decreases by 20\"\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\nA useful way to visualize all the odds ratios and their uncertainty simultaneously is a **forest plot**. To make this plot, we first need to convert the output of our model into a \"tidy\" format where each row is a predictor variable and each column is a different attribute of the model fit:\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom) \ntidy_model = tidy(chd_glm, conf.int = TRUE, exponentiate = TRUE)\nhead(tidy_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  term           estimate std.error statistic  p.value  conf.low conf.high\n  <chr>             <dbl>     <dbl>     <dbl>    <dbl>     <dbl>     <dbl>\n1 (Intercept)    0.000243   0.715     -11.6   2.84e-31 0.0000591  0.000977\n2 male1          1.74       0.109       5.09  3.57e- 7 1.41       2.16    \n3 age            1.07       0.00668     9.50  2.12e-21 1.05       1.08    \n4 education      0.954      0.0494     -0.962 3.36e- 1 0.865      1.05    \n5 currentSmoker1 1.07       0.157       0.452 6.51e- 1 0.788      1.46    \n6 cigsPerDay     1.02       0.00624     2.87  4.05e- 3 1.01       1.03    \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\nThen we plot the predictors vs their corresponding coefficient estimates with confidence intervals:\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy_model[-1,] |>\n  ggplot( aes(x = estimate, y = term)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", color = \"#E69F00\") +\n  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +\n  geom_point(size = 3, color = \"#009E73\") +\n  scale_x_log10() +\n  labs(x = \"Odds Ratio (log scale)\",\n       y = \"Variables\",\n       title = \"Forest Plot of Odds Ratios with 95% Confidence Intervals\",\n       subtitle = \"Vertical line at OR = 1 indicates no effect\") +\n  theme_minimal() +\n  theme(axis.text.y = element_text(size = 8))\n```\n\n::: {.cell-output-display}\n![](notes3_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\n\nEach point is the estimated odds ratio for that predictor and the horizontal bars show the 95% confidence interval. Predictors whose confidence intervals cross the vertical line at 1 are not significantly associated with CHD.\n\n## The Confusion Matrix and Classification Metrics\n\nBefore we dive into evaluating our logistic regression model, we need to develop better tools for measuring classification performance. So far we have been using accuracy as our metric for classification performance. However, accuracy alone can be misleading, especially when the classes are imbalanced. To see why, let's start with a motivating example.\n\n### A Medical Testing Example\n\nSuppose these is a town of 10,000 people where about 3% have had COVID-19. A particular antibody test has:\n\n- A **93.8% chance** of correctly detecting antibodies in someone who has had COVID (this is called *recall* or *sensitivity* or *true positive* rate^[Its annoying that there are so many names for these terms but that just tells you the concepts are important! They have appeared across many different applications leading to the independent development of different terminologies.])\n- A **95.6% chance** of correctly showing no antibodies in someone who hasn't had COVID (this is called *specificity* or *true negative* rate)\n\nWe can organize the results of testing everyone in town into a **confusion matrix** where the rows tell the truth and the columns tell us the predictions^[Although be careful of always assuming this orientation. You'll see examples where truth and predictions are switched!]\n\n|  | Test Positive | Test Negative |\n|--|--|--|\n| **Actually COVID** | 282 | 18 |\n| **Actually No COVID** | 388 | 9312 |\n\nFrom this table we can compute several metrics:\n\n**Accuracy** — what fraction of all predictions were correct?\n$$accuracy = \\frac{282 + 9312}{10000} = 0.959$$\n\nLooks pretty good! But let's dig deeper.\n\n**Recall** — what is the probability of testing positive given that you actually have the disease?\n$$recall = \\frac{282}{282 + 18} = 0.938$$\n\n**Specificity** — what is the probability of testing negative given that you actually don't have the disease?\n$$specificity = \\frac{9312}{9312 + 388} = 0.960$$\n\n**Balanced Accuracy** — the average of sensitivity and specificity:\n$$balanced\\ accuracy = \\frac{0.938 + 0.960}{2} = 0.949$$\n\n**Precision (Positive Predictive Value)** — what is the probability that you actually have the disease given that you tested positive?\n$$precision = \\frac{282}{282 + 388} = 0.421$$\n\nNotice something alarming: even though accuracy is 95.9%, if you test positive there is only a **42% chance** you actually have COVID! This happens because the disease is rare - most positive tests are false positives from the large pool of healthy people. This is why accuracy alone is misleading for imbalanced problems.\n\n### Precision vs Recall Tradeoff\n\nHere's an intuitive way to think about the tension between precision and recall. Suppose I show you 10 cards and then shuffle them into a deck of 100. I go through each card and ask if it was one of the ones you saw:\n\n- If you always say \"Yes\", your **recall will be 100%** — you'll never miss a card you saw. But your **precision will be terrible** since you're also saying yes to 90 cards you never saw.\n- If you only say \"Yes\" when you're completely certain, your **precision will be high** but you'll **miss many cards** you actually saw.\n\nThis tradeoff appears constantly in classification problems (eg. spam filters, medical tests, fraud detection) and is one of the reasons we need multiple metrics rather than just accuracy.\n\n### Which Metric Should We Use?\n\nIt depends on the problem:\n\n- **Medical diagnosis** — recall (sensitivity) is usually more important since missing a true case (false negative) is more costly than a false alarm (where you can always do additional testing to rule it out)\n- **Spam detection** — precision matters more since falsely flagging legitimate emails is more annoying than letting some spam through\n- **Balanced accuracy** is a good default when you want to treat both types of errors equally, especially for imbalanced classes\n\nWith this framework in place, let's now evaluate our logistic regression model on the Framingham heart disease data.\n\n## Computing Validation Metrics\n\nFor a fitted model, the predictions $\\hat y$ take the place of the test results in the example above while the values of the outcome $y$ are the truth to which we compare. It is more common to display the confusion matrix for test data so we'll start by refitting our model using a 70-30 split\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2178)\nn=nrow(framingham)\ns=sample(n,round(.7*n,0))\ntrain_set=framingham[s,]\ntest_set=framingham[-s,]\ntrain_glm=glm(TenYearCHD ~ ., data = train_set, family = \"binomial\")\n```\n:::\n\n\n\n\n\n\n\n\n\nThen we calculate the predictions for the test set\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny=test_set$TenYearCHD\nprobs=predict(train_glm,test_set,type=\"response\")\nyhat=ifelse(probs>0.5,1,0)\n```\n:::\n\n\n\n\n\n\n\n\n\nTo create a confusion matrix, we simply count true positives (places where actual and predicted are both positive), true negatives (both negative), false positives (predicted true but actual false) and false negatives (predicted false but actual true) in the test set, storing the result in a matrix: \n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  TP = sum(yhat == 1 & y == 1)\n  TN = sum(yhat ==  0 & y == 0)\n  FP = sum(yhat == 1 & y == 0)\n  FN = sum(yhat == 0 & y == 1)\n  confusion_matrix = matrix(c(TP, FP, FN, TN), \n                             nrow = 2,\n                             dimnames = list(\"Actual\" = c(1, 0),\n                                             \"Predicted\" = c(1, 0)))\n  print(confusion_matrix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Predicted\nActual  1   0\n     1 12 150\n     0  7 928\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nFrom here, we compute any metrics we want such\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc=(TP+TN)/(TP+TN+FN+FP)\nrecall=TP / (TP + FN)\nprecision= TP/(TP+FP)\nspec=TN/(TN+FP)\nbal_acc=(recall+spec)/2\ncat(\"Accuracy:\",acc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAccuracy: 0.8568824\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nRecall:\", recall)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nRecall: 0.07407407\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nPrecision:\", precision)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPrecision: 0.6315789\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nSpecificity:\",spec)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSpecificity: 0.9925134\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nBalanced Acc:\",bal_acc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBalanced Acc: 0.5332937\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\nHere you notice the issue with accuracy. The model with a 0.5 cutoff does very well at ruling out CHD when it is absent (high specificity), but it is shitty at recall. The balanced accuracy reflects this fact.  \n\nCan we improve the balanced accuracy by defining a different cutoff for prediction? We'll investigate that in the next section, but first, here is a helper function that computes all of the above metrics in one package deal:\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalculate_metrics <- function(predicted, actual, positive) {\n  # Inputs: predicted values, actual values, positive value (eg. \"1\" or \"Yes\")\n  # outputs: COnfusion matrix, recall, precision, specificity, accuracy, bal accuracy\n  # Dependencies: requires tidyverse or at least forcats\n  \n  actual <- fct_relevel(factor(actual), positive)\n  predicted <- fct_relevel(factor(predicted), positive)\n  \n  TP <- sum(predicted == positive & actual == positive)\n  FP <- sum(predicted == positive & actual != positive)\n  TN <- sum(predicted != positive & actual != positive)\n  FN <- sum(predicted != positive & actual == positive)\n  \n  precision <- ifelse((TP + FP) > 0, TP / (TP + FP), NA)\n  recall <- ifelse((TP + FN) > 0, TP / (TP + FN), NA)\n  specificity <- ifelse((TN + FP) > 0, TN / (TN + FP), NA)\n  accuracy <- (TP + TN) / (TP + FP + TN + FN)\n  balanced_accuracy <- (recall + specificity) / 2\n  \n  confusion_matrix <- matrix(c(TP, FP, FN, TN), nrow = 2,\n                             dimnames = list(\"Actual\" = c(\"Positive\", \"Negative\"),\n                                             \"Predicted \" = c(\"Positive\", \"Negative\")))\n  return(list(\n    Confusion_Matrix = confusion_matrix,\n    Recall = recall,\n    Precision = precision,\n    Specificity = specificity,\n    Accuracy = accuracy,\n    Balanced_Accuracy = balanced_accuracy\n  ))\n}\n```\n:::\n\n\n\n\n\n\n\n\n\nHere's an example of how to apply the test set in our framingham model using the default cutoff of 0.5:\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalculate_metrics(yhat, y, \"1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Confusion_Matrix\n          Predicted \nActual     Positive Negative\n  Positive       12      150\n  Negative        7      928\n\n$Recall\n[1] 0.07407407\n\n$Precision\n[1] 0.6315789\n\n$Specificity\n[1] 0.9925134\n\n$Accuracy\n[1] 0.8568824\n\n$Balanced_Accuracy\n[1] 0.5332937\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n## Choosing an Optimal Cutoff\n\nLet's try a range of cutoffs for predicting CHD starting at 0 and ending at 0.9 and check the balanced accuracy of each:\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny=test_set$TenYearCHD\nprobs=predict(train_glm,test_set,type=\"response\")\ncutoffs = seq(0, 0.9, by = 0.05)\nresults = map_dfr(cutoffs, function(cutoff) {\n  yhat=ifelse(probs>cutoff,1,0)\n  m = calculate_metrics(yhat, y, \"1\")\n\n  tibble(\n    cutoffs = cutoff,\n    bal_acc=m$Balanced_Accuracy\n  )\n})\n\nplot(results$cutoffs, results$bal_acc,\n     xlab = \"Cutoff for Positive Classification\",\n     ylab = \"Balanced Accuracy\")\n```\n\n::: {.cell-output-display}\n![](notes3_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\n\nThe optimal cutoff and its corresponding balanced accuracy are:\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(paste(\"Best cutoff is\", cutoffs[which.max(results$bal_acc)]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Best cutoff is 0.15\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(sprintf(\"Balanced Accuracy is %.3f\", max(results$bal_acc)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Balanced Accuracy is 0.673\"\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\nFinally, let's look at the full set of metrics for the optimal cutoff:\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyhat=ifelse(probs>cutoffs[which.max(results$bal_acc)], 1, 0)\ncalculate_metrics(yhat, y, \"1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Confusion_Matrix\n          Predicted \nActual     Positive Negative\n  Positive      113       49\n  Negative      329      606\n\n$Recall\n[1] 0.6975309\n\n$Precision\n[1] 0.2556561\n\n$Specificity\n[1] 0.6481283\n\n$Accuracy\n[1] 0.6554239\n\n$Balanced_Accuracy\n[1] 0.6728296\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\nThe specificity is smaller than what we got using the 0.5 cutoff, but this is offset by a rise in recall to create an overall gain in balanced accuracy.\n\n## Bonus: ROC curves\n\nReceiver Operator Characteristic (ROC) curves are a tool that machine learning has borrowed from signal processing as an alternative metric for measuring model success. In an ROC curve, we plot the recall (true positive rate) vs $1-$ sensitivity (false positive rate). This curve is compared with the line $y=x$ for reference. Here is what this looks like for the framingham model:\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny=test_set$TenYearCHD\nprobs=predict(train_glm,test_set,type=\"response\")\ncutoffs = seq(0, 0.9, by = 0.05)\nresults <- map_dfr(cutoffs, function(cutoff) {\n\n  yhat <- ifelse(probs > cutoff, 1, 0)\n  m <- calculate_metrics(yhat, y, \"1\")\n\n  tibble(\n    cutoff = cutoff,\n    TPR = m$Recall,\n    FPR = 1 - m$Specificity\n  )\n})\nplot(results$FPR, results$TPR,\n     xlab = \"False Positive Rate\",\n     ylab = \"True Positive Rate\")\nabline(a=0,b=1,col=\"#D55e00\")\n```\n\n::: {.cell-output-display}\n![](notes3_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\n\nThe optimal cutoff will be the one which gets us the most gain in TPR before we start losing FPR. One way to measure this is as the point with the greatest vertical distance from the line $y=x$, frequently measured by a statistic called _Youden's J_. For our example, this would be \n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults$J = results$TPR - results$FPR\n\nbest = results[which.max(results$J), ]\nbest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  cutoff   TPR   FPR     J\n   <dbl> <dbl> <dbl> <dbl>\n1   0.15 0.698 0.352 0.346\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\nInterestingly, this gave the same value as optimizing balanced accuracy.\n\nThe _area under the ROC curve_ (or AUC) is another commonly used metric for assessing the fit of a classification scheme which doesn't choose a cutoff at all. Instead, it just measures a model by the overall area under its ROC. We could compute this by choosing a finer grid of points and using numeric integration, but instead we'll introduce the pROC package for this purpose\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pROC)\nroc_result=roc(response=y,predictor=probs)\nauc(roc_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArea under the curve: 0.7388\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\nThe AUC can be interpreted as follows. Suppose that we give each of our data points a score based on the model's assigned probability that this point corresponds to a positive results. AUC is then the probability that a random positive case is awarded a higher score than a random negative case. In other words, if I select one CHD and one none CHD, AUC gives the probability that the model scores the actual CHD case higher than the false one. The closer AUC is to 1, the better the model fits the data. \n\n## What's next\n\nOne issue with analyzing our model and choosing optimal thresholds based on a single training-testing set pair is that the results may dependent on the starting seed or at least we should check if they do. In our example above, I tried several different starting seeds and the results were fairly consistent which gives us greater confidence in our recommendations. In the next module, we will systematize this process of repeated sampling or _resampling_ in the context of cross-validation. We'll then see some applications to variable selection as well. \n\n## Practice\n\nThe `palmerpenguins` package contains a famous dataset called `penguins` on the size measurements for adult penguins foraging near Palmer Station, Antartica. After you have installed this package, load it into R and create a new dataset which drops all NAs by running the following code. \n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\npenguins2=penguins |>\n  drop_na()\n```\n:::\n\n\n\n\n\n\n\n\n\n1. Split the data into training-testing sets according to a 70-30 split and fit a logistic model to the training data to predict sex (female/male) based on bill length, bill depth flipper length, and body mass. Which predictors were significant? \n2. Calculate a confusion matrix, accuracy, recall, precision, specificity, and balanced accuracy for your model on the test set (using the standard predict positive if probability > 0.5 threshold). Comment on the results.\n3. (Bonus) Can you find a threshold which beats the predictions from 2 in terms of either balanced accuracy or Youden's J distance? \n",
    "supporting": [
      "notes3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}