<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Decision Trees of Life – Statistical Learning Methods</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d4be639c637f3db3c684c66cefad7e0c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Statistical Learning Methods</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-1" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 1</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-1">    
        <li>
    <a class="dropdown-item" href="../module-01/notes1.html">
 <span class="dropdown-text">Module 1.1: Introduction to Statistical Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-01/notes2.html">
 <span class="dropdown-text">Module 1.2: Prediction for Simple Linear Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-01/notes3.html">
 <span class="dropdown-text">Module 1.3: Inference for Simple Linear Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-01/supplement.html">
 <span class="dropdown-text">Module 1 Theory: A deeper look at finding coefficients</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-01/rtools.html">
 <span class="dropdown-text">Module 1 R Tools: Introduction to ggplot2 and tidyverse</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-2" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 2</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-2">    
        <li>
    <a class="dropdown-item" href="../module-02/notes1.html">
 <span class="dropdown-text">Module 2.1: Multiple Regression Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-02/notes2.html">
 <span class="dropdown-text">Module 2.2: Enriching Linear Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-02/notes3.html">
 <span class="dropdown-text">Module 2.3: Regression Diagnostics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-02/notes_bonus.html">
 <span class="dropdown-text">Module 2 Bonus: The F Test</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-02/supplement.html">
 <span class="dropdown-text">Module 2 Theory Supplement</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-3" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 3</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-3">    
        <li>
    <a class="dropdown-item" href="../module-03/notes1.html">
 <span class="dropdown-text">Module 3.1: Introduction to Classification</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-03/notes2.html">
 <span class="dropdown-text">Module 3.2: Logistic Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-03/notes3.html">
 <span class="dropdown-text">Module 3.3: Evaluating Classifiers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-03/supplement.html">
 <span class="dropdown-text">Module 3 Theory Supplement: Finding Logistic Regression Coefficients</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-4" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 4</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-4">    
        <li>
    <a class="dropdown-item" href="../module-04/notes1.html">
 <span class="dropdown-text">Module 4.1: Cross Validation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-04/notes2.html">
 <span class="dropdown-text">Module 4.2: Feature Selection</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-04/notes3.html">
 <span class="dropdown-text">Module 4.3: Regularization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-04/rTools.html">
 <span class="dropdown-text">Module 4 R Tools: Tuning Hyperparameters with Tidymodels</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-5" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 5</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-5">    
        <li>
    <a class="dropdown-item" href="../module-05/notes1.html">
 <span class="dropdown-text">Module 5.1: Principal Component Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-05/notes2.html">
 <span class="dropdown-text">Module 5.2: K-means Clustering</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-05/notes3.html">
 <span class="dropdown-text">Module 5.3: Hierarchical Clustering</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-05/supplement.html">
 <span class="dropdown-text">Module 5 Theory Supplement: PCA vs SVD</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../module-05/rtools.html">
 <span class="dropdown-text">Module 5 R Tools: fviz-ness</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-6" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 6</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-6">    
        <li class="dropdown-header">Notes 1: …</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-7" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 7</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-7">    
        <li class="dropdown-header">Notes 1: …</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-module-8" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Module 8</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-module-8">    
        <li class="dropdown-header">Notes 1: …</li>
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Decision Trees of Life</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The last module provided a brief introduction to unsupervised learning, focusing on principal component analysis (PCA) for dimensionality reduction and clustering techniques for identifying patterns in unlabeled data. While those methods help uncover structure without predefined labels, we now shift our focus back to supervised learning, where models are trained using labeled examples. In this module, we explore a powerful and intuitive class of supervised models based on decision trees. Decision trees form the foundation of many machine learning algorithms, offering a structured way to make predictions by recursively partitioning data based on feature values. We will examine how decision trees operate, their strengths and limitations, and how they serve as the building blocks for more advanced ensemble methods.</p>
<p>As always, we begin by loading necessary shit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">71</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>df_url<span class="ot">=</span><span class="st">"https://raw.githubusercontent.com/jmayberr/math133-stat-learning-fall2026/refs/heads/main/Datasets/election2016.csv"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>election2016<span class="ot">=</span><span class="fu">read.csv</span>(df_url)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>cb_palette <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#000000"</span>,  <span class="co"># black</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#E69F00"</span>,  <span class="co"># orange</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#56B4E9"</span>,  <span class="co"># sky blue</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#009E73"</span>,  <span class="co"># bluish green</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#F0E442"</span>,  <span class="co"># yellow</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#0072B2"</span>,  <span class="co"># blue</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#D55E00"</span>,  <span class="co"># vermillion</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"#CC79A7"</span>   <span class="co"># reddish purple</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we get down to it.</p>
</section>
<section id="regression-trees" class="level2">
<h2 class="anchored" data-anchor-id="regression-trees">Regression Trees</h2>
<p>Decision trees can be used in both classification and regression problems. For this reason, they are often referred to with the acronym CART (Classification And Regression Trees) although RPART (Recursive PARTitioning) is one of the primary R packages to use when building such models. The “C” of CART is more natural to explain from an application perspective, but the “R” part is easier to explain mathematically so we will start with the latter. In contrast to the usual flow of mathematical exposition, we will actually start with an example and then explain how it works. In case you’re not sick of it yet, we’ll be using our favorite election dataset with trump.vote as the response</p>
<p>Pictures speak louder than words so let’s start with a visual. It requires loading three new packages, one which loads the name model building function <code>rpart()</code>, one which just loads the color brewer palettes, and one which loads the aptly named visualization function <code>fancyRpartplot()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rattle)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>trump_tree<span class="ot">=</span><span class="fu">rpart</span>(trump.vote<span class="sc">~</span>.,<span class="at">data=</span>election2016[,<span class="dv">2</span><span class="sc">:</span><span class="dv">10</span>])</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">fancyRpartPlot</span>(trump_tree,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">palettes =</span> <span class="st">"Reds"</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">sub =</span> <span class="st">"Trump Vote Tree"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notes1_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>You can also get this information (and more) in a raw form by printing the model output</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(trump_tree)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>n= 50 

node), split, n, deviance, yval
      * denotes terminal node

 1) root 50 0.49805000 0.4990000  
   2) non.citizen&gt;=0.055 19 0.07367368 0.4147368 *
   3) non.citizen&lt; 0.055 31 0.20678710 0.5506452  
     6) median.income&gt;=57196 9 0.05688889 0.4788889 *
     7) median.income&lt; 57196 22 0.08460000 0.5800000  
      14) metro&gt;=0.725 9 0.01575556 0.5422222 *
      15) metro&lt; 0.725 13 0.04710769 0.6061538 *</code></pre>
</div>
</div>
<p>How do we interpret these results? Let’s start from the top and work our way down. The boxes are called nodes. Our tree has seven of them. The top box is called the root. The segments that connect nodes are called branches<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. The places where two branches depart from a node are called splits. The five nodes at the bottom are called terminal nodes or leaves<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. All this makes sense based on common knowledge of real world trees (except that these trees are upside down growing from the sky).</p>
<p>Looking from the top-down in our tree, the root node has three numbers in it: 0.5, n=50, and 100%. These represent, respectively, the average trump.vote for all states, the number of states in our dataset, and the percentage of all states being summarized in the root node (all of them). After that node, there is a split with the rule: non.citizen &gt;= 0.055. To the left, it says “Yes” and to the right it says “No”. That means that the node to the left of the split represents all states with at least 5.5% non-citizens. The numbers in the node say that there were n=19 states in this group (38% of all states) and the average trump.vote in these states was 0.41. On the right of the split, is a node for the states which had fewer than 5.5% non-citizens. For these states, the average trump share was 14 points higher (0.55 as opposed to 0.41). States under this node are further split by Median Income with wealthier states to the left and less wealthy states to the right. The dividing line is a median income of 57000. States with a low median income are further broken up by whether they are at least 73% metro or not.</p>
<p>All in all, these splitting end up grouping the states into four categories with increasing levels of redness</p>
<ul>
<li>High Non-citizen (Most Blue - 41% trump on average)</li>
<li>Low Non-citizen, High Median Income (48% Trump vote)</li>
<li>Low Non-citizen, Low Income, High Metro (54%)</li>
<li>Low Non-citizen, Low Income, Low Metro (61%)</li>
</ul>
<p>You can see which states landed in each leaf using the “where” command although the numbers do not exactly match the leaf numbers in the tree<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#election2016$leaf=trump_tree$where</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(trump_tree<span class="sc">$</span>where)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 2  4  6  7 
19  9  9 13 </code></pre>
</div>
</div>
<p>The states in the predicted “reddest” node are</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>election2016<span class="sc">$</span>state[trump_tree<span class="sc">$</span>where<span class="sc">==</span><span class="dv">7</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Alabama"       "Arkansas"      "Idaho"         "Kansas"       
 [5] "Kentucky"      "Maine"         "Mississippi"   "Montana"      
 [9] "Nebraska"      "Oklahoma"      "South Dakota"  "West Virginia"
[13] "Wyoming"      </code></pre>
</div>
</div>
<p>Makes sense<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>Now that you know how to read a tree, let’s talk a little bit about how it works. Next class we’ll discuss the corresponding classification problem.</p>
</section>
<section id="greedy-trees" class="level2">
<h2 class="anchored" data-anchor-id="greedy-trees">Greedy Trees</h2>
<p>The end goal of a tree is to partition the sample into leaves that are as “similar” as possible, kind of like in K-means clustering. The difference between regression trees and K-means is what we mean by “similar”. In K-means (an unsupervised algorithm), “similar” means that the <span class="math inline">\(x\)</span> values are as close together as possible. In regression trees (a supervised algorithm) we want the <span class="math inline">\(y\)</span> values to be as close as possible. In other words, we are trying to find a set of <span class="math inline">\(K\)</span> leaves <span class="math inline">\(L_1,...,L_K\)</span> which minimizes the sum of squared errors<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>: <span class="math display">\[
SSE =\sum_{j=1}^K \sum_{y_{ij} \in L_j} (y_{ij}-\bar{y}_j)^2
\]</span> where <span class="math inline">\(\bar{y}_j\)</span> is the mean of all observations in leaf <span class="math inline">\(j\)</span>.</p>
<p>OK, now that we have a preliminary idea of the function we might want to minimize, the next question is how in the world do we search through all possible splits of variables to find this optimal split? Well, you are unlikely to get THE optimal but you could get AN optimal by using what’s called a top-down greedy approach.</p>
<p>In this algorithm, we start by looking at all possible splits of the form <span class="math inline">\(X_i &lt; x\)</span> where <span class="math inline">\(X_i\)</span> can be any of our predictors and <span class="math inline">\(x\)</span> can be any real number (note: if <span class="math inline">\(X_i\)</span> is categorical instead of continuous, we instead look at all possible splits into subsets of possible values). In the example above, the optimal first split was non.citizen &lt; 0.055. You can see other splits attempted by the algorithm using the “splits” argument of the output</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(trump_tree<span class="sc">$</span>splits)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              count ncat   improve     index       adj
non.citizen      50    1 0.4368823     0.055 0.0000000
median.income    50    1 0.3469531 57196.000 0.0000000
metro            50    1 0.3233172     0.840 0.0000000
white.pov        50   -1 0.2210384     0.105 0.0000000
non.white        50    1 0.1472139     0.215 0.0000000
metro             0    1 0.8600000     0.840 0.6315789</code></pre>
</div>
</div>
<p>Looking at these first five entries, the first is the one used by the tree because it led to the largest improvement in SSE over the root node (the SSE of the root node would be the total sum of squares). The value of improve is the percent change in SSE from the parent node to its children: <span class="math display">\[improve = 1 - (SSE_{Children}/SSE_{Parent})\]</span> This statistic is akin to looking at the increase in <span class="math inline">\(R^2\)</span> when comparing a reduced model (without the split) to a full model (with the split). Splits based on other variables led to smaller improvements, but the values listed under index are the splitting rules that would have been used if that variable was selected. The last entry above for metro is different in that it gives a surrogate split. This means that it is the best substitute for non-citizen in the case of missing data. Its value of improve is instead the level of its agreement with the non.citizen split. So the 0.86 above means that 86% of all states would go in the same split direction if we used metro instead of non-citizen.</p>
<p>Another important output from the rpart function is the cptable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>trump_tree<span class="sc">$</span>cptable</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          CP nsplit rel error    xerror      xstd
1 0.43688228      0 1.0000000 1.0742865 0.1651265
2 0.13110774      1 0.5631177 0.7155531 0.1452760
3 0.04364371      2 0.4320100 0.6967316 0.1494352
4 0.01000000      3 0.3883663 0.7523601 0.1884560</code></pre>
</div>
</div>
<p>The cptable summarizes statistics of the primary splits used in the final tree construction, starting with node 0. The best way to read this table is to pretend you are trying to make a decision on whether or not to make split. For example, in the first row, we are trying to decide if we want to make the first split by non.citizen which we have decided is the best possible split we could make. Then we should interpret the columns as follows:</p>
<ul>
<li>CP (complexity parameter): This is the minimum required improvement in SSE to keep the split. In other words, the first split above would lead to a 0.43688228 reduction in relative SSE so we should keep it if that threshold seems acceptable. Otherwise, we shouldn’t make it. The second split would lead to an additional 0.1311 reduction<br>
</li>
<li>nsplit: This is how many splits we have already made</li>
<li>rel error: This is the current relative error of our tree (SSE/SST).</li>
<li>xerror: Average relative error obtained from cross-validation (default is to use 10 folds)</li>
<li>xstd: Standard deviation of xerror from cross-validation.</li>
</ul>
<p>That description of CP may sound confusing and interestingly I once had a fun and somewhat contentious argument<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> with chatGPT about how it is computed in rpart until I realized the best thing to do is just to look at an example. Suppose that we are trying to analyze the first split in our trump tree above. First we compute the SST as a baseline for comparison</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>SST<span class="ot">=</span><span class="fu">sum</span>((election2016<span class="sc">$</span>trump.vote<span class="sc">-</span><span class="fu">mean</span>(election2016<span class="sc">$</span>trump.vote))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>SST</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.49805</code></pre>
</div>
</div>
<p>Next, we look at what SSE we would get after the split.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>node1<span class="ot">=</span>dplyr<span class="sc">::</span><span class="fu">filter</span>(election2016,non.citizen<span class="sc">&gt;=</span><span class="fl">0.055</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>node2<span class="ot">=</span>dplyr<span class="sc">::</span><span class="fu">filter</span>(election2016,non.citizen<span class="sc">&lt;</span><span class="fl">0.055</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>SSEn1<span class="ot">=</span><span class="fu">sum</span>((node1<span class="sc">$</span>trump.vote<span class="sc">-</span><span class="fu">mean</span>(node1<span class="sc">$</span>trump.vote))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>SSEn2<span class="ot">=</span><span class="fu">sum</span>((node2<span class="sc">$</span>trump.vote<span class="sc">-</span><span class="fu">mean</span>(node2<span class="sc">$</span>trump.vote))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>SSE1<span class="ot">=</span>SSEn1<span class="sc">+</span>SSEn2</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>re1<span class="ot">=</span><span class="dv">1</span><span class="sc">-</span>SSE1<span class="sc">/</span>SST</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>re1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4368823</code></pre>
</div>
</div>
<p>This relative error is the first entry in the cp table.</p>
<p>Now to explain the second cp value, let’s look at the error we would get from splitting node 2 into its potential children</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>SSEn22<span class="ot">=</span><span class="fu">sum</span>((node2<span class="sc">$</span>trump.vote<span class="sc">-</span><span class="fu">ifelse</span>(node2<span class="sc">$</span>median.income<span class="sc">&gt;=</span><span class="dv">57196</span>,<span class="fl">0.48</span>,<span class="fl">0.58</span>))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>SSE2<span class="ot">=</span>SSEn1<span class="sc">+</span>SSEn22</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>re2<span class="ot">=</span><span class="dv">1</span><span class="sc">-</span>SSE2<span class="sc">/</span>SST</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>re2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5679677</code></pre>
</div>
</div>
<p>Notice that the difference is the CP:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>re2<span class="sc">-</span>re1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1310854</code></pre>
</div>
</div>
<p>So at the second step, we would keep the split if an improvement of 0.13 seems worth it.</p>
<p>Cp is the most common measure of how much we gain from each split and can be used in “pruning”” back a tree (see below). Note that rpart uses cp=0.01 as one of its stopping rules for when to quit attempting splits: as soon as there are no more splits which gain you more than 1% in relative error, they aren’t worth making according to rpart. The other stopping criteria is based on node sizes: rpart will not attempt a split on a node with fewer than 20 observations. Both of these criteria can be modified with the appropriate arguments in rpart; see the help file for more details.</p>
<p>The fourth and fifth columns give the mean and std of the cross-validation errors from the model fit (using <span class="math inline">\(K=10\)</span> folds by default). You can plot these to see if it there is any over-fitting going on:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(trump_tree,<span class="at">upper=</span><span class="st">"splits"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notes1_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Notice that the trees with one or two splits have a lower cross validation error which suggests we “pruning” may want to avoid overfitting by “pruning back” the tree to one with a larger cp<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>. The dashed line in the plot shows one SD above the best model and some people prefer to use the simplest model which drops below this line. In our case, that would be the tree with only one split and this tree would correspond to any cp value between 0.43688228 (the first entry in the cp table) and 0.13110774 (the second). The function to obtain pruned trees is aptly named prune.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>trump_prune<span class="ot">=</span><span class="fu">prune</span>(trump_tree,<span class="at">cp=</span>.<span class="dv">4</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fancyRpartPlot</span>(trump_prune,<span class="at">sub=</span><span class="st">"Pruned Tree"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notes1_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We could also prune to the two split example</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>trump_prune2<span class="ot">=</span><span class="fu">prune</span>(trump_tree,<span class="at">cp=</span>.<span class="dv">09</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fancyRpartPlot</span>(trump_prune2,<span class="at">sub=</span><span class="st">"Pruned Tree 2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notes1_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>or the three, but I think you get the point by now.</p>
</section>
<section id="up-next" class="level2">
<h2 class="anchored" data-anchor-id="up-next">Up Next</h2>
<p>Trees can also be used for classification problems and we’ll see how next class. In the meantime, if you want some more practice, try a regression tree on the mtcars data using mpg as the outcome (Group work 12).</p>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>or as my kids used to say, the “bones” of the tree.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Guess what my kids called those…<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>In fact these numbers, unlike those in the tree, are the actual node numbers from top to bottom, left to right. In the visual, the left and right children of a parent labeled <span class="math inline">\(n\)</span> are labeled <span class="math inline">\(2n\)</span> and <span class="math inline">\(2n+1\)</span>. <a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Although Maine is a bit of an outlier because their electoral votes are split.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>This is very similar to what we do in OLS except that here, the predictions are piecewise functions, defined on leaf <span class="math inline">\(j\)</span> as <span class="math inline">\(\bar{y}_j\)</span>.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Don’t worry kids, we apologized and made up after.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Very confusingly, the cp on the x-axis here is not exactly the same as the cp in the table, but is the geometric mean of the last two cp values. Honestly, I don’t really know why.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>