---
title: "Class Notes for 09-02"
format: html
---

LOad dataset

```{r}
df_url="https://raw.githubusercontent.com/jmayberr/math133-stat-learning-fall2026/refs/heads/main/Datasets/Advertising.csv"
advertising=read.csv(df_url)
head(advertising)
```

```{r}
sales_lm_full=lm(sales~.,data=advertising)
summary(sales_lm_full)
```

Drop newspaper

```{r}
sales_lm_reduced=update(sales_lm_full,.~.-newspaper)
summary(sales_lm_reduced)

```

Creating 3D Plot

```{r}
library(plotly)
advertising |>
  plot_ly(x=~TV,y=~radio,z=~sales) |>
  add_markers(size=3,color=I("black"))
```

```{r}
x_lims=c(0,300) #Limits for x-variable
y_lims=c(0,50) #Limits for y-variable
xy_grid=expand.grid(TV=x_lims,radio=y_lims) #pairs of x-y values
yhat=predict(sales_lm_reduced,xy_grid) #Calculates predictions (z)
z=matrix(yhat,nrow=2,ncol=2) #Turns predictions into matrix
```

```{r}
advertising |>
  plot_ly(x=~TV,y=~radio,z=~sales) |>
  add_markers(size=3,color=I("black")) |>
  add_surface(x=~x_lims,y=~y_lims,z=~t(z),colorscale="Portland")
```

Added Variable Plots

```{r}
library(car)
avPlots(sales_lm_reduced)
```
